name: PHP and MySQL Recipes
name_cn: PHP和MySQL秘籍
slug: php-and-mysql-recipes
toc:
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '#'
  - 第 1 章：安装与配置
- - '##'
  - 配方 1-1：安装 PHP
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 1-2：配置 PHP
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 1-3：编译 PHP
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 1-4：安装 MySQL
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 1-5：虚拟机
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 2 章：类与对象
- - '##'
  - 配方 2-1：编写一个简单的类
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-2：编写一个基类
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-3：编写一个抽象类
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-4：编写一个接口
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-5：将类成员作为常规函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-6：保护数据和方法
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-7：混合静态与对象上下文
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-8：引用类成员
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-9：类的实例化
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-10：打印对象
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-11：变量重载
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-12：序列化类型与对象
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-13：复制对象
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-14：将对象用作函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-15：重载方法
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-16：调试对象
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-17：在不使用类的情况下使用对象
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-18：目录迭代
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-19：编写可复用代码
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-20：避免名称冲突
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 2-21：首次使用时自动加载类
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 3 章：执行数学运算
- - '##'
  - 配方 3-1：更改数字的基数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-2：转换为不同进制数值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-3：在整数中存储二进制值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-4：设置和清除二进制位
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-5：使用十六进制数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-6：通过二进制移位提升性能
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-7：浮点数的四舍五入
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-8：生成随机数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-9：使用对数函数表达比率
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-10：计算未来值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-11：使用三角函数计算距离与方向
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 3-12：处理复数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 4 章：处理数组
- - '##'
  - 技巧 4-1：创建数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 4-2：修改数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 4-3：添加数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 4-4：数组的数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 4-5：遍历数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 4-6：排序数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 4-7：将数组作为栈使用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 4-8：切片与拼接数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 4-9：调试数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 4-10：存储数组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 5 章：日期与时间
- - '##'
  - 配方 5-1：处理时区
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 5-2：创建时间戳
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 5-3：处理日期
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 5-4：显示时间戳
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 5-5：使用 ISO 格式
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 5-6：处理周数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 6 章：字符串
- - '##'
  - 配方 6-1：创建字符串
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 6-2：处理字符串中的字符
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 6-3：替换字符
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 6-4：使用 Heredoc 和 Newdoc 创建长字符串
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 6-5：字符串转义
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 6-6：字符串格式化
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 6-10：显示 HTML 实体
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 6-11：为文件生成哈希值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 6-12：存储密码
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 7 章：文件和目录
- - '##'
  - 配方 7-1：包含与引入
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-2：读取文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-3：写入文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-4：复制、重命名和删除文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-5：文件属性
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-6：权限
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-7：符号链接
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-8：目录
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-9：CSV 文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-10：流
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 7-11：流上下文
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 7-12：文件迭代器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 7-13：下载文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 7-14：上传文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 7-15：压缩文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 8 章：动态图像处理
- - '##'
  - 技巧 8-1：创建图像
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-2：调整图像大小
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-3：裁剪图像
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-4：旋转图像
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-5：翻转图像
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-6：添加水印
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-7：更改颜色
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-8：在图像上绘图
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-9：透明度
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 8-10：添加文本
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 9 章：正则表达式
- - '##'
  - 技巧 9-1：格式验证
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 9-2：子模式
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 9-3：字符串替换
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 10 章：变量
- - '##'
  - 技巧 10-1：转换变量类型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-2：分配内存
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-3：确定内存使用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-4：利用变量作用域
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-5：利用超全局变量避免全局变量问题
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-6：确定变量类型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-7：使用引用减少内存使用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-8：使用常量
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-9：可变变量
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-10：比较变量
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-11：处理字符串
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-12：处理浮点数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-13：特殊语言结构
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-14：遍历数组值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 10-15：生成输出
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 11 章：函数
- - '##'
  - 技巧 11-1：调用函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 11-2：变量作用域
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 11-3：传递参数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 11-4：可选参数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 11-5：类型声明
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 11-6：返回值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 11-7：检查函数是否存在
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 11-8：计算出的函数名
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 11-9：匿名函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 11-10：可变参数列表
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 12 章：Web 基础
- - '##'
  - 方法 12-1：标头
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-2：$_GET 和 $_POST
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-3：Cookie
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-4：服务器变量
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-5：会话数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-6：内容类型与内容配置
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-7：缓存
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-8：远程内容
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-9：HTTPS 协议
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 12-10：AJAX 请求
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 13 章：创建和使用表单
- - '##'
  - 配方 13-1：表单元素
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 13-2：默认值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 13-3：表单验证
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 13-4：表单生成
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 13-5：文件上传
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 13-6：表单数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 14 章：XML、RSS、WDDX 与 SOAP
- - '##'
  - 配方 14-1：使用 XML 交换数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 14-2：生成 XML 响应
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 14-3：通过 RSS 共享数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 秘诀 14-4：消费 RSS 推送源
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 秘诀 14-5：标准数据交换
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方案 14-6：SOAP 服务器与客户端
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 15 章：使用 JSON 进行数据交换
- - '###'
  - 方法 15-1：使用 AJAX 获取数据
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '###'
  - 方法 15-2：返回 JSON
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 工作原理
- - '##'
  - 方案 15-3：消费 JSON API
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 15-4：JSON API
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 技巧 15-5：调用 API
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 配方 15-6：API 身份验证
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 16 章：使用 MySQL 数据库
- - '##'
  - 食谱 16-1：连接数据库
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 食谱 16-2：持久连接
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 食谱 16-3：获取数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 食谱 16-4：插入数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 食谱 16-5：更新数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 食谱 16-6：删除数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 食谱 16-7：模式信息
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
