name: Typed PHP
name_cn: Typed PHP 入门指南
slug: typed-php
toc:
- - '#'
  - 强类型 PHP
- - '##'
  - 更健壮的类型，更整洁的代码
- - '###'
  - 克里斯托弗·皮特
- - '##'
  - 引言
- - '###'
  - 为何写这本书
- - '###'
  - 目标读者
- - '###'
  - 过程式 / 面向对象
- - '####'
  - 过程式编程
- - '####'
  - 面向对象编程
- - '####'
  - 哪种最好？
- - '####'
  - PHP 是哪种？
- - '###'
  - 原生函数的不一致性
- - '####'
  - 零星的下划线
- - '####'
  - 零星的缩写
- - '####'
  - 不一致的参数顺序
- - '####'
  - 正则表达式 / 字符串
- - '####'
  - 名词 / 动词
- - '####'
  - 奇怪的返回值
- - '###'
  - 结论
- - '##'
  - 结构
- - '###'
  - 装箱
- - '###'
  - 解析类型
- - '####'
  - 标量类型
- - '####'
  - 函数
- - '####'
  - 类
- - '####'
  - 正则表达式
- - '###'
  - 命名空间函数
- - '####'
  - Composer 自动加载
- - '####'
  - 未来的便利功能
- - '###'
  - 结论
- - '##'
  - 扩展
- - '###'
  - Vagrant + Phansible
- - '####'
  - 安装
- - '####'
  - 配置
- - '####'
  - Vagrant 命令
- - '###'
  - SPL 类型
- - '####'
  - 安装 SPL 类型
- - '####'
  - 使用 SPL 类型
- - '###'
  - 标量对象
- - '####'
  - 安装标量对象
- - '####'
  - 使用标量对象
- - '###'
  - Zephir
- - '####'
  - 安装 Zephir
- - '####'
  - 使用 Zephir
- - '###'
  - 结论
- - '##'
  - 设计
- - '###'
  - 使用哪种方法
- - '####'
  - 命名空间方法
- - '####'
  - 标量对象 / SPL Types
- - '####'
  - Zephir
- - '###'
  - 如何构建类型结构
- - '####'
  - 类型解析
- - '####'
  - 链式调用
- - '####'
  - 组合数字类型
- - '##'
  - 如何测试
- - '###'
  - PHPUnit
- - '###'
  - 应该测试什么？
- - '###'
  - 何时编写测试？
- - '###'
  - 推荐阅读
- - '##'
  - 如何打包
- - '###'
  - 编写 `Readme` 文件
- - '###'
  - 几个示例
- - '###'
  - 测试说明
- - '###'
  - 安装说明
- - '###'
  - 许可证
- - '###'
  - 贡献指南
- - '##'
  - 结论
- - '###'
  - 面向未来设计
- - '##'
  - 附录
- - '###'
  - PHP 实现
- - '###'
  - Zephir 实现
- - '###'
  - JavaScript 实现
