name: Pro PHP MVC
name_cn: PHP MVC 高级指南
slug: pro-php-mvc
toc:
- - '#'
  - 目录概览
- - '##'
  - 引言
- - '###'
  - 本书面向的读者
- - '###'
  - 本书不会教授的内容
- - '###'
  - 本书将教授的内容
- - '###'
  - 源代码
- - '##'
  - 第 1 章：MVC 简介
- - '###'
  - 什么是 MVC？
- - '###'
  - 控制器
- - '###'
  - MVC 的优势
- - '###'
  - 流行的 MVC 框架
- - '####'
  - CodeIgniter
- - '####'
  - Zend Framework
- - '####'
  - CakePHP
- - '###'
  - 设计模式
- - '####'
  - 单例模式
- - '####'
  - 注册表模式
- - '####'
  - 工厂模式
- - '####'
  - 观察者模式
- - '###'
  - 创建我们自己的框架
- - '####'
  - 目标
- - '##'
  - 第 2 章：基础
- - '###'
  - 目标
- - '###'
  - 自动加载
- - '###'
  - 命名空间
- - '###'
  - 惰性加载
- - '###'
  - 异常
- - '###'
  - 类型方法
- - '###'
  - 不依赖于公有属性
- - '###'
  - 配置
- - '##'
  - 第 3 章：基类
- - '###'
  - 目标
- - '###'
  - Getter 和 Setter
- - '###'
  - 魔术方法
- - '####'
  - 清单 3-5. `__call()` 方法
- - '####'
  - 清单 3-6. 使用 `__call()` 实现 Getter/Setter
- - '###'
  - 添加内省功能
- - '###'
  - 透明的 Getter/Setter
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 4 章：配置
- - '###'
  - 目标
- - '###'
  - 关联数组
- - '###'
  - INI 文件
- - '###'
  - 理解配置驱动程序
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 5 章：缓存
- - '###'
  - 目标
- - '###'
  - 性能瓶颈
- - '###'
  - 代码
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 6 章：注册表
- - '###'
  - 目标
- - '###'
  - 单例
- - '###'
  - 单例模式与注册表模式
- - '###'
  - 注册表模式
- - '###'
  - 问题
- - '###'
  - 答案
- - '##'
  - 第 7 章：路由
- - '###'
  - 目标
- - '###'
  - 定义路由
- - '###'
  - 路由类
- - '####'
  - Router 类
- - '#####'
  - 清单 7-7. 处理已定义路由
- - '#####'
  - 清单 7-8. 处理预先存在的路由
- - '#####'
  - 清单 7-9. 路由器 `_pass()` 方法
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 8 章：模板
- - '###'
  - 目标
- - '###'
  - 理念
- - '###'
  - 替代方案
- - '###'
  - 实现
- - '###'
  - 优势
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 9 章：数据库
- - '###'
  - 目标
- - '###'
  - 实现
- - '####'
  - 连接器
- - '####'
  - 查询
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习题
- - '##'
  - 第 10 章：模型
- - '###'
  - 目标
- - '###'
  - 理念
- - '###'
  - 实现
- - '###'
  - 构建 SQL
- - '###'
  - 修改记录
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 11 章：测试
- - '###'
  - 目标
- - '###'
  - 单元测试
- - '###'
  - 测试类
- - '###'
  - 缓存
- - '###'
  - 测试覆盖范围
- - '###'
  - 测试
- - '###'
  - 配置
- - '###'
  - Model
- - '###'
  - 模板
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 12 章：结构
- - '###'
  - 目标
- - '###'
  - 数据库
- - '###'
  - 用户与内容管理
- - '###'
  - 文件夹
- - '###'
  - 问题
- - '###'
  - 答案
- - '##'
  - 第 13 章：引导
- - '###'
  - 目标
- - '###'
  - URL 重写
- - '####'
  - '`Index.php`'
- - '###'
  - 配置
- - '###'
  - 数据库
- - '###'
  - 缓存
- - '###'
  - 控制器
- - '###'
  - 视图
- - '###'
  - 渲染（Rendering）
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 14 章：注册与登录
- - '###'
  - 目标
- - '###'
  - 共享库
- - '###'
  - 用户模型
- - '###'
  - 注册
- - '###'
  - 会话
- - '###'
  - 登录
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 15 章：搜索
- - '###'
  - 目标
- - '###'
  - 扩展实现
- - '###'
  - URL 请求
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 16 章：设置
- - '###'
  - 目标
- - '###'
  - 验证
- - '###'
  - 按需验证
- - '###'
  - 问题
- - '###'
  - 答案
- - '##'
  - 第 17 章：共享
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 18 章：照片
- - '###'
  - 目标
- - '###'
  - 如何上传文件
- - '###'
  - 用户照片
- - '####'
  - 代码清单 18-4. `_upload()`方法
- - '####'
  - 代码清单 18-5. `register()`操作
- - '####'
  - 代码清单 18-6. `settings()`操作
- - '####'
  - 代码清单 18-7. 文件输入
- - '###'
  - 练习
- - '##'
  - 第 19 章：扩展
- - '###'
  - 目标
- - '###'
  - Foxy
- - '###'
  - 自定义 CSS 字体
- - '###'
  - 构建代理
- - '####'
  - 使用代理
- - '###'
  - Imagine
- - '###'
  - 观察者模式
- - '###'
  - 同步性
- - '###'
  - 插件
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 20 章：管理
- - '###'
  - 目标
- - '###'
  - 什么是 CMS？
- - '###'
  - 管理员
- - '###'
  - 登录
- - '###'
  - 用户
- - '###'
  - 照片管理
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 21 章：测试
- - '###'
  - 目标
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 22 章：CodeIgniter：引导程序
- - '###'
  - 目标
- - '###'
  - 为什么选择 CodeIgniter？
- - '###'
  - 为什么不用 CodeIgniter？
- - '###'
  - URL 重写
- - '###'
  - 路由
- - '###'
  - CodeIgniter 与我们的框架对比
- - '###'
  - 模型
- - '##'
  - 第 23 章：CodeIgniter：MVC
- - '###'
  - 控制器
- - '####'
  - 清单 23-7. `application/views/users/register.php`
- - '####'
  - 清单 23-8. `application/controllers/users.php`（节选）
- - '####'
  - 清单 23-9. `application/views/users/login.php`
- - '####'
  - 清单 23-10. `application/controllers/users.php`（节选）
- - '###'
  - 搜索
- - '###'
  - 问题
- - '###'
  - 答案
- - '##'
  - 第 24 章：CodeIgniter：扩展
- - '###'
  - 文件上传
- - '###'
  - 第三方库
- - '###'
  - 扩展核心
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 25 章：CodeIgniter：测试
- - '###'
  - 目标
- - '###'
  - 工具
- - '####'
  - 替代方案
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 26 章：Zend Framework：引导
- - '###'
  - 目标
- - '###'
  - 为什么选择 Zend Framework？
- - '###'
  - 为什么不选择 Zend Framework？
- - '###'
  - 开始设置
- - '###'
  - 路由
- - '###'
  - 控制器
- - '####'
  - '`settingsAction()` 方法'
- - '####'
  - '`searchAction()` 方法'
- - '###'
  - 问题
- - '##'
  - 第 27 章：Zend Framework：MVC
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 28 章：Zend Framework：扩展
- - '###'
  - 目标
- - '###'
  - 文件上传
- - '###'
  - 第三方库
- - '####'
  - 安装`PEAR`
- - '#####'
  - Windows
- - '#####'
  - Unix/Linux/BSD
- - '#####'
  - Mac OS X
- - '####'
  - 安装`PHPUnit`
- - '###'
  - 运行测试
- - '###'
  - 添加测试
- - '###'
  - 问题
- - '###'
  - 答案
- - '##'
  - 第 29 章：Zend Framework：测试
- - '##'
  - 第 30 章：CakePHP：引导
- - '###'
  - 目标
- - '###'
  - 为什么选择 CakePHP？
- - '###'
  - 为什么不选择 CakePHP？
- - '###'
  - 环境搭建
- - '###'
  - 路由
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习题
- - '##'
  - 第 31 章：CakePHP：MVC
- - '###'
  - 目标
- - '###'
  - 模型里有什么？
- - '###'
  - 控制器
- - '###'
  - 收尾工作
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 32 章：CakePHP：扩展
- - '###'
  - 目标
- - '###'
  - 文件上传
- - '###'
  - 第三方库
- - '####'
  - 插件
- - '####'
  - Vendor 目录
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 第 33 章：CakePHP：测试
- - '###'
  - 目标
- - '###'
  - 测试
- - '###'
  - 问题
- - '###'
  - 答案
- - '###'
  - 练习
- - '##'
  - 附录 A：搭建 Web 服务器
- - '###'
  - 目标
- - '###'
  - Windows 系统
- - '####'
  - 步骤 1
- - '####'
  - 步骤 2
- - '####'
  - 步骤 3
- - '###'
  - Linux 系统
- - '####'
  - 步骤 1
- - '####'
  - 步骤 2
- - '####'
  - 步骤 3
- - '####'
  - 步骤 4
- - '###'
  - MAC OS X 系统
- - '####'
  - 步骤 1
- - '####'
  - 步骤 2
- - '####'
  - 步骤 3
- - '###'
  - 你成功通过了！
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J, K
- - '###'
  - L
- - '###'
  - M, N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - V
- - '###'
  - W
- - '###'
  - W, X, Y
- - '###'
  - Z
- - '###'
  - 其他
