name: PHP Beginners Course
name_cn: PHP 初学者教程
slug: php-beginners-course
toc:
- - '#'
  - PHP 初学者课程
- - '##'
  - 版权页
- - '##'
  - 目录
- - '##'
  - 前言
- - '###'
  - 欢迎！
- - '###'
  - 前置要求
- - '##'
  - 第 1 天
- - '###'
  - PHP —— 定义与历史
- - '###'
  - 搭建开发环境（Windows、Linux 或 Mac OS）
- - '####'
  - Windows
- - '####'
  - 服务器安装与配置
- - '####'
  - Linux
- - '####'
  - MacOS
- - '####'
  - 文本编辑器
- - '###'
  - 第一个 PHP 程序（欢迎全世界）
- - '###'
  - 注释代码
- - '###'
  - 算术运算（基本运算）
- - '###'
  - 组合多个变量（数组）
- - '###'
  - 对数组排序
- - '###'
  - 多维数组
- - '##'
  - 第 2 天
- - '###'
  - 用用户信息填充变量（GET / POST）
- - '###'
  - 识别并读取 GET 变量
- - '###'
  - 案例分析（`switch` / `case`）
- - '###'
  - 用于重复任务的循环（`While` / `For` / `Foreach`）
- - '####'
  - '`While()` 循环'
- - '##'
  - 第 3 天
- - '###'
  - PHP 循环与日期/时间函数
- - '####'
  - While 循环
- - '####'
  - For 循环
- - '####'
  - Foreach 循环
- - '###'
  - 日期与时间
- - '####'
  - Date()
- - '####'
  - microtime()
- - '####'
  - 使用 mktime() 为 Date() 指定时间点
- - '####'
  - strtotime()
- - '####'
  - 格式选项
- - '#####'
  - 日
- - '#####'
  - 周
- - '#####'
  - 月
- - '#####'
  - 年
- - '#####'
  - 时间
- - '#####'
  - 时区
- - '#####'
  - 完整日期/时间
- - '###'
  - 文本函数（字符串操作）
- - '####'
  - str_replace
- - '####'
  - PHP 字符串处理函数
- - '#####'
  - '`substr()`'
- - '#####'
  - '`strtolower()`'
- - '#####'
  - '`strtoupper()`'
- - '#####'
  - '`strpos()`'
- - '#####'
  - '`strrpos()`'
- - '#####'
  - '`strlen()`'
- - '#####'
  - '`explode()`'
- - '#####'
  - '`implode()`'
- - '###'
  - 编写自己的函数
- - '###'
  - 将代码拆分到多个文件中
- - '##'
  - 第 4 天
- - '###'
  - 使用数据库（MySQL）存储和读取信息
- - '####'
  - 在 PHP 中连接到数据库
- - '####'
  - 创建新数据库
- - '####'
  - 选择我们的数据库
- - '####'
  - 创建表
- - '####'
  - 向数据库写入数据
- - '####'
  - 从数据库中检索数据
- - '####'
  - 从数据库中删除数据
- - '###'
  - 文件操作（读取/写入文件）
- - '####'
  - PHP 文件操作与安全指南
- - '#####'
  - 文件打开模式
- - '#####'
  - 保存到文本文件
- - '#####'
  - 从文本文件读取
- - '#####'
  - 管理会话
- - '##'
  - 第五天：编写整洁的代码（一年后仍能理解）
- - '###'
  - PHP 脚本安全性
- - '####'
  - 原则：永远不要信任来自外部的数据
- - '####'
  - 防范 SQL 注入
- - '####'
  - 如何保护自己？
- - '####'
  - 保持密码加密
- - '####'
  - 为密码加盐
- - '###'
  - 网站推荐
- - '####'
  - PHP
- - '####'
  - SQL
- - '###'
  - 书籍推荐
- - '####'
  - '《PHP and MySQL for Dynamic Web Sites, Fourth Edition: Visual QuickPro Guide》'
- - '####'
  - '《Head First PHP & MySQL: A Brain-Friendly Guide Kindle Edition》'
- - '####'
  - 《PHP Objects, Patterns, and Practice》
- - '####'
  - 《Wikibook PHP Programming》
- - '##'
  - 结语
