name: PHP 8 Basics
name_cn: PHP 8 基础指南
slug: php-8-basics
toc:
- - '#'
  - 引言
- - '##'
  - 本书面向的读者
- - '##'
  - 先决条件
- - '##'
  - 下载源代码
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于贡献者
- - '#'
  - 1. 入门指南
- - '##'
  - 为什么要使用 PHP？
- - '##'
  - 使用 PHP
- - '##'
  - 为什么要用 PHP、Nginx 和 MySQL？
- - '##'
  - 安装 Docker
- - '###'
  - Windows
- - '###'
  - Mac OS
- - '###'
  - Linux
- - '##'
  - 安装 Docker-Compose
- - '###'
  - 开发环境
- - '##'
  - 本章小结
- - '#'
  - 2. PHP 基础
- - '##'
  - 变量
- - '##'
  - 将错误用作工具
- - '##'
  - 对象
- - '##'
  - 总结
- - '#'
  - 3. 函数、类与特征
- - '##'
  - OOP
- - '###'
  - 回顾类的定义
- - '###'
  - 类的可见性
- - '####'
  - Public
- - '####'
  - Protected
- - '####'
  - Private
- - '##'
  - 深入探讨类继承
- - '##'
  - 多态性与抽象类
- - '###'
  - 常量
- - '###'
  - 构造与析构
- - '###'
  - 特征（Trait）
- - '###'
  - 命名空间
- - '##'
  - 总结
- - '#'
  - 4. 数据与数据类型
- - '##'
  - PHP 数据类型
- - '##'
  - PHP 数据类型：标量类型
- - '###'
  - 布尔型
- - '###'
  - 整型
- - '###'
  - 浮点型
- - '###'
  - 字符串
- - '##'
  - PHP 字符串函数
- - '###'
  - '`substr()`'
- - '###'
  - '`strlen()`'
- - '###'
  - '`str_replace()`'
- - '###'
  - '`trim()`'
- - '###'
  - '`strpos()`'
- - '###'
  - '`strtolower()`'
- - '###'
  - '`strtoupper()`'
- - '###'
  - '`is_string()`'
- - '###'
  - '`strstr()`'
- - '##'
  - PHP 数据类型：复合类型
- - '###'
  - 数组
- - '###'
  - 对象
- - '##'
  - PHP 数据类型：特殊类型
- - '###'
  - 'NULL'
- - '###'
  - 资源
- - '##'
  - 总结
- - '#'
  - 5. 表单数据
- - '##'
  - PHP POST 表单
- - '###'
  - PHP GET 表单
- - '##'
  - 总结
- - '#'
  - 6. 数组
- - '##'
  - PHP 索引数组和关联数组
- - '##'
  - PHP 多维数组
- - '##'
  - PHP 数组函数
- - '###'
  - '`array_change_key_case`'
- - '###'
  - '`array_chunk`'
- - '###'
  - '`array_column`'
- - '##'
  - PHP 数组函数参考
- - '###'
  - '`array_column()`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_combine`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_count_values()`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_diff_assoc`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_diff_key`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_diff_uassoc`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_diff_ukey`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_diff`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_fill_keys`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_fill`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_filter`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_flip`'
- - '##'
  - PHP 数组函数参考
- - '###'
  - '`array_flip()`'
- - '###'
  - '`array_intersect_assoc`'
- - '###'
  - '`array_intersect_key`'
- - '###'
  - '`array_intersect_uassoc`'
- - '###'
  - '`array_intersect_ukey`'
- - '###'
  - '`array_intersect`'
- - '###'
  - '`array_is_list`'
- - '###'
  - '`array_key_exists`'
- - '###'
  - '`array_key_first`'
- - '###'
  - '`array_key_last`'
- - '###'
  - '`array_keys`'
- - '###'
  - '`array_map`'
- - '###'
  - '`array_merge_recursive`'
- - '##'
  - PHP 数组函数参考
- - '###'
  - '`array_merge_recursive()`'
- - '###'
  - '`array_merge()`'
- - '###'
  - '`array_multisort()`'
- - '###'
  - '`array_pad()`'
- - '###'
  - '`array_pop()`'
- - '###'
  - '`array_product()`'
- - '###'
  - '`array_push()`'
- - '###'
  - '`array_rand()`'
- - '###'
  - '`array_reduce()`'
- - '###'
  - '`array_replace_recursive()`'
- - '###'
  - '`array_replace()`'
- - '###'
  - '`array_replace()`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_reverse`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_search`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_shift`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_slice`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_splice`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_sum`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_udiff_assoc`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_udiff_uassoc`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_udiff`'
- - '####'
  - 参数
- - '####'
  - 返回值
- - '###'
  - '`array_uintersect_assoc`'
- - '###'
  - '`array_uintersect_uassoc`'
- - '###'
  - '`array_uintersect`'
- - '###'
  - '`array_unique`'
- - '###'
  - '`array_unshift`'
- - '###'
  - '`end`'
- - '###'
  - '`extract`'
- - '###'
  - '`in_array`'
- - '###'
  - '`key_exists`'
- - '###'
  - '`key`'
- - '###'
  - '`krsort`'
- - '###'
  - '`ksort`'
- - '###'
  - '`list`'
- - '###'
  - '`natcasesort`'
- - '###'
  - '`natsort`'
- - '###'
  - '`next`'
- - '##'
  - PHP 数组函数
- - '###'
  - '`next()`'
- - '###'
  - '`prev()`'
- - '###'
  - '`range()`'
- - '###'
  - '`reset()`'
- - '###'
  - '`rsort()`'
- - '###'
  - '`shuffle()`'
- - '###'
  - '`sort()`'
- - '###'
  - '`uasort()`'
- - '###'
  - '`uksort()`'
- - '###'
  - '`usort()`'
- - '##'
  - 总结
- - '#'
  - 7. 会话与 Cookie
- - '##'
  - PHP 会话
- - '##'
  - PHP Cookie
- - '##'
  - 删除 Cookies
- - '##'
  - 总结
- - '#'
  - 8. 对象
- - '##'
  - 总结
- - '#'
  - 9. PHP 异常、验证和正则表达式
- - '##'
  - PHP 异常
- - '##'
  - PHP 表单验证
- - '##'
  - PHP 正则表达式
- - '###'
  - 正则表达式修饰符
- - '###'
  - 正则表达式元字符
- - '###'
  - 正则表达式方括号
- - '###'
  - 正则表达式量词
- - '###'
  - 正则表达式函数
- - '##'
  - 总结
- - '#'
  - 10. PHP 与 MySQL 协同工作
- - '##'
  - PHP 与 MySQL 的通信
- - '###'
  - 运行中的 Docker 容器
- - '###'
  - PHP 通过 MySQLi 方法通信
- - '###'
  - PHP 通过 PDO 方法通信
- - '####'
  - MySQLi 的优势
- - '####'
  - PDO 的优势
- - '##'
  - PHP 连接数据库
- - '##'
  - 总结
- - '#'
  - 11. 数据
- - '##'
  - 规划新数据库
- - '##'
  - 创建新数据库
- - '##'
  - 总结
- - '#'
  - 12. 带数据库的网站
- - '##'
  - 总结
- - '#'
  - 13. 框架介绍
- - '##'
  - 框架简介
- - '##'
  - 框架的优缺点
- - '###'
  - 使用框架的优点
- - '###'
  - 使用框架的缺点
- - '####'
  - 3. 学习曲线
- - '###'
  - MVC 模式
- - '###'
  - 框架的不同层级
- - '###'
  - 不同类型的框架
- - '##'
  - PHP 框架与标准
- - '###'
  - 微框架
- - '###'
  - 全栈框架
- - '###'
  - Composer 的作用
- - '###'
  - PHP 标准建议 (PSR) 介绍
- - '####'
  - 自动加载
- - '####'
  - 接口
- - '####'
  - HTTP
- - '####'
  - 编码风格
- - '##'
  - 相关 PSR 标准
- - '##'
  - PHP 框架
- - '##'
  - 如何选择框架
- - '##'
  - 总结
- - '#'
  - Laravel 简介
- - '##'
  - Laravel 简介
- - '##'
  - 安装 Laravel
- - '###'
  - 数据库设置与配置
- - '###'
  - 数据库迁移
- - '###'
  - 控制器路由
- - '###'
  - 注册视图表单
- - '###'
  - 将用户数据存储到数据库
- - '##'
  - 总结
- - '#'
  - 15. Symfony 入门
- - '##'
  - Symfony 简介
- - '##'
  - Symfony 框架概述
- - '###'
  - 做事流程
- - '###'
  - 一种理念
- - '###'
  - 一个社区
- - '###'
  - Symfony 的特性
- - '####'
  - 1. 用于 Web 项目的 PHP 框架
- - '####'
  - 2. 易于使用
- - '####'
  - 3. 稳定可靠
- - '####'
  - 4. 可扩展
- - '####'
  - 5. 高性能
- - '####'
  - 6. 依赖注入
- - '####'
  - 7. 模块化组件
- - '####'
  - 8. 分析器工具
- - '#####'
  - 1. 命令行工具
- - '#####'
  - 2. 文档与支持
- - '##'
  - 安装 Symfony
- - '##'
  - 创建一个 Symfony 应用程序
- - '##'
  - 基础 Symfony 应用结构分析
- - '##'
  - 本章小结
- - '#'
  - 16. 基础 Symfony 应用
- - '##'
  - 创建新 Symfony 项目
- - '##'
  - 数据库设置与配置
- - '###'
  - 控制器路由
- - '##'
  - 注册视图表单
- - '##'
  - 在数据库中存储用户数据
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - PHP 数组函数与相关概念
- - '###'
  - 数组函数列表
- - '###'
  - 其他重要概念
- - '####'
  - A
- - '####'
  - B
- - '####'
  - C
- - '####'
  - D
- - '####'
  - E
- - '####'
  - F
- - '##'
  - G
- - '###'
  - '`__get()` 方法'
- - '###'
  - '`GET` 方法'
- - '###'
  - '`PHP CRUD GET` 方法'
- - '###'
  - '`getMenuName()` 方法'
- - '###'
  - Getter 方法
- - '###'
  - '`git status`'
- - '##'
  - H
- - '###'
  - Hash 辅助函数
- - '###'
  - '`header.php`'
- - '###'
  - '`htmlspecialchars PHP` 函数'
- - '###'
  - 超文本传输协议 (HTTP)
- - '##'
  - I, J
- - '###'
  - '`inc/` 目录'
- - '###'
  - '`include_once` 函数'
- - '###'
  - 索引数组
- - '###'
  - '`index_key`'
- - '###'
  - 独立对象
- - '###'
  - 继承
- - '###'
  - Instagram 插件
- - '###'
  - 整数
- - '###'
  - 接口
- - '###'
  - '`IntlException`'
- - '###'
  - '`IOException`'
- - '###'
  - '`__isset()` 方法'
- - '###'
  - '`is_string()` 函数'
- - '##'
  - K
- - '###'
  - 键
- - '###'
  - '`key_compare_func`'
- - '###'
  - '`krsort()`'
- - '###'
  - '`ksort()`'
- - '##'
  - L
- - '###'
  - Laravel 数据库表创建
- - '###'
  - Laravel PHP 框架
- - '####'
  - 常见任务
- - '####'
  - 控制器路由
- - '####'
  - 数据库迁移
- - '####'
  - 命令
- - '####'
  - 创建与表选项
- - '####'
  - 默认模板
- - '####'
  - 目录
- - '####'
  - 迁移表结构
- - '####'
  - 修改
- - '####'
  - 创建新迁移文件
- - '####'
  - 输出
- - '####'
  - phpMyAdmin
- - '####'
  - 撤销更改
- - '####'
  - 时间戳值
- - '####'
  - 用户注册功能
- - '####'
  - 用户表结构
- - '####'
  - 数据库设置与配置
- - '####'
  - 安装
- - '####'
  - MVC 设计模式
- - '####'
  - 注册视图表单
- - '####'
  - 存储用户数据
- - '####'
  - Web 应用程序框架
- - '###'
  - Laravel 项目目录结构
- - '###'
  - Laravel 表结构
- - '###'
  - Laravel 网页
- - '###'
  - 学习曲线
- - '###'
  - 长度
- - '###'
  - '`list()`'
- - '###'
  - '`localhost:8000/chapter2/vartest.php`'
- - '##'
  - M
- - '###'
  - '`main2.php`'
- - '###'
  - '`main3.php`'
- - '###'
  - '`main.php` 文件'
- - '###'
  - '`ManagerRegistry`'
- - '###'
  - 操作
- - '###'
  - '`MessageClass::EXIT_MESSAGE`'
- - '###'
  - 元字符
- - '###'
  - 微框架
- - '###'
  - 创建迁移
- - '###'
  - '`migrations` 表'
- - '###'
  - 迁移表结构
- - '###'
  - 模型-视图-控制器 (MVC)
- - '###'
  - 修饰符
- - '###'
  - '`modify_cookie.php`'
- - '###'
  - 多维数组
- - '###'
  - MVC 层
- - '###'
  - MyISAM 存储引擎
- - '###'
  - '`mysql` 适配器'
- - '###'
  - '`mysql` 连接'
- - '###'
  - MySQL
- - '###'
  - MySQL 8.0
- - '###'
  - MySQLi 优势
- - '###'
  - MySQLi 方法
- - '###'
  - MySQL PDO 参数绑定
- - '##'
  - N
- - '###'
  - 命名空间
- - '###'
  - '`natcasesort()`'
- - '###'
  - '`natsort()`'
- - '###'
  - 创建新数据库
- - '####'
  - 基本设计
- - '####'
  - 目录
- - '####'
  - Docker
- - '####'
  - MySQL
- - '####'
  - 命令
- - '####'
  - 容器
- - '####'
  - '`mysql-db` 属性'
- - '####'
  - '`show tables` 命令'
- - '####'
  - 结构
- - '####'
  - 表
- - '###'
  - '`newtest.php`'
- - '###'
  - '`next()`'
- - '###'
  - Nginx
- - '###'
  - Nowdoc 语法
- - '###'
  - 'NULL'
- - '###'
  - 数字
- - '##'
  - O
- - '###'
  - 面向对象编程 (OOP)
- - '####'
  - 降低复杂度
- - '####'
  - 数据保护
- - '####'
  - 封装
- - '####'
  - 自由与创造力
- - '####'
  - 继承
- - '####'
  - 多态
- - '###'
  - 对象
- - '####'
  - 赋值
- - '####'
  - 类更改的影响
- - '####'
  - 复合数据类型
- - '####'
  - 数据操作
- - '####'
  - 定义
- - '####'
  - 功能
- - '####'
  - 函数
- - '####'
  - 实例化
- - '####'
  - OOP 概念
- - '####'
  - 示例
- - '####'
  - 用户自定义类
- - '####'
  - 调用 `var_dump`
- - '###'
  - 可选偏移量参数
- - '##'
  - P
- - '###'
  - 包管理
- - '###'
  - PATCH 方法
- - '###'
  - PHP
- - '####'
  - 数组
- - '####'
  - 框架
- - '####'
  - 库
- - '####'
  - MySQL 预处理语句
- - '####'
  - 正则表达式，字符序列
- - '####'
  - 保留字
- - '####'
  - 变量
- - '###'
  - PHP 8
- - '###'
  - '`php bin/console doctrine:database:create`'
- - '###'
  - '`php bin/console doctrine:migrations:migrate`'
- - '###'
  - '`php bin/console make:controller UserController`'
- - '###'
  - '`php bin/console make:entity`'
- - '###'
  - '`php bin/console make:migration`'
- - '###'
  - PHP 与 MySQL 通信
- - '####'
  - Docker 开发环境
- - '####'
  - '`mysql:8.0`'
- - '####'
  - MySQLi 方法
- - '####'
  - PDO 版本
- - '###'
  - PHP 连接数据库
- - '####'
  - '`addUser.php`'
- - '####'
  - '`artisan`'
- - '####'
  - ASC 和 DESC 选项
- - '####'
  - 条件
- - '####'
  - 数据库变量
- - '####'
  - 数据组织
- - '####'
  - '`db.php` 文件'
- - '####'
  - '`execute` 方法'
- - '####'
  - 逻辑处理
- - '####'
  - MySQL
- - '####'
  - '`mysqli` 构造函数'
- - '####'
  - MySQLi
- - '####'
  - ORDER 查询
- - '####'
  - 数据填充
- - '####'
  - SELECT 查询
- - '####'
  - '`users` 表'
- - '####'
  - '`DB_HOST`'
- - '####'
  - '`mysqli` 对象'
- - '####'
  - '`query` 对象'
- - '###'
  - PHP CRUD POST 方法
- - '###'
  - PHP 数据对象 (PDO)
- - '####'
  - 优势
- - '####'
  - 方法
- - '###'
  - PHP 数据类型
- - '####'
  - 分类
- - '####'
  - 复合类型
- - '#####'
  - 数组
- - '#####'
  - 对象
- - '####'
  - 数据存储
- - '####'
  - 标量类型
- - '#####'
  - 布尔型
- - '#####'
  - 定义
- - '#####'
  - 浮点型
- - '#####'
  - 整型
- - '#####'
  - 短语
- - '#####'
  - 字符串
- - '####'
  - 特殊类型
- - '#####'
  - 'NULL'
- - '#####'
  - 资源
- - '###'
  - PHP 异常
- - '####'
  - catch 块
- - '####'
  - '`checkMyNum()`'
- - '####'
  - Finally 块
- - '####'
  - 机制
- - '####'
  - 运行时错误
- - '####'
  - 带函数的特殊类
- - '####'
  - '`throw`'
- - '####'
  - '`throwable`'
- - '####'
  - try 块
- - '###'
  - PHP 表单数据处理
- - '###'
  - PHP 表单验证
- - '####'
  - 电子邮件
- - '####'
  - 空字段
- - '####'
  - 错误消息
- - '####'
  - 文件
- - '####'
  - HTML 网页表单
- - '####'
  - 字母和空格
- - '####'
  - 正则表达式函数
- - '####'
  - 特殊字符
- - '####'
  - 值
- - '###'
  - PHP 框架互操作性组 (PHP-FIG)
- - '###'
  - PHP 基础知识
- - '####'
  - 错误
- - '####'
  - 对象
- - '####'
  - 变量
- - '####'
  - 动词
- - '###'
  - PHP GET 表单
- - '####'
  - '`basicForm.php`'
- - '####'
  - '`functions.php`'
- - '####'
  - 值设置
- - '####'
  - 变量设置
- - '####'
  - name 和 email 变量
- - '###'
  - PHP 全局变量 `$_POST`
- - '###'
  - phpMyAdmin
- - '####'
  - 界面
- - '####'
  - 模型
- - '####'
  - 工具
- - '###'
  - PHP POST 表单
- - '####'
  - 代码结果
- - '####'
  - 开发者思维
- - '####'
  - 电子邮件服务器
- - '####'
  - '`filter_var` 函数'
- - '####'
  - '`functions.php`'
- - '####'
  - HTML 元素
- - '####'
  - HTML 表单
- - '####'
  - 方法设置
- - '####'
  - POST 变量
- - '####'
  - 特殊字符
- - '####'
  - 用户输入
- - '###'
  - PHP 编程语言
- - '####'
  - 命令行
- - '####'
  - 数据组织与传递
- - '####'
  - 事实上的编程语言
- - '####'
  - 开发环境
- - '####'
  - 重要性
- - '####'
  - 脚本集合
- - '####'
  - 服务器端脚本
- - '###'
  - '`PHP. $_REQUEST`'
- - '###'
  - PHP 标准推荐 (PSR)
- - '####'
  - 自动加载
- - '####'
  - 编码风格
- - '####'
  - 目标/目的
- - '####'
  - HTTP
- - '####'
  - 接口
- - '####'
  - 规范
- - '####'
  - 标准列表
- - '###'
  - PHP 字符串函数
- - '####'
  - '`is_string()`'
- - '####'
  - '`strlen()`'
- - '####'
  - '`strpos()`'
- - '####'
  - '`str_replace()`'
- - '####'
  - '`strstr()`'
- - '####'
  - '`strtolower()`'
- - '####'
  - '`strtoupper()`'
- - '####'
  - '`substr()`'
- - '####'
  - '`trim()`'
- - '###'
  - 规划新数据库
- - '####'
  - CHAR 数据类型
- - '####'
  - 选择 CHAR 而非 VARCHAR
- - '###'
  - 数据库引擎选择
- - '####'
  - 连接条件
- - '####'
  - MySQL EXISTS 函数
- - '####'
  - 多态
- - '###'
  - POST
- - '###'
  - Postman
- - '###'
  - '`preg_match()`'
- - '###'
  - '`preg_match_all()`'
- - '###'
  - '`preg_replace()`'
- - '###'
  - '`preserve_keys`'
- - '###'
  - '`prev()`'
- - '###'
  - 私有类
- - '###'
  - 受保护类
- - '###'
  - 公有类
- - '###'
  - PUT 方法
- - '##'
  - Q
- - '##'
  - R
- - '###'
  - '`/register`'
- - '###'
  - 注册视图表单
- - '###'
  - 正则表达式
- - '###'
  - '`remove_session.php`'
- - '###'
  - '`替换` 数组'
- - '###'
  - '`请求` 面板'
- - '###'
  - '`reset()`'
- - '###'
  - 资源
- - '###'
  - 行级锁定
- - '###'
  - '`rsort()`'
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X
- - '##'
  - Y, Z
