name: Beginning PHP and PostgreSQL E-Commerce
name_cn: PHP 和 PostgreSQL 电子商务入门指南
slug: beginning-php-and-postgresql-e-commerce
toc:
- - '#'
  - PHP 与 PostgreSQL 电子商务入门：从新手到专家
- - '#'
  - 第一部分 — 开发阶段一
- - '##'
  - 第 1 章：开启电子商务网站
- - '##'
  - 第 2 章：奠定基础
- - '##'
  - 第 3 章：创建产品目录：第一部分
- - '##'
  - 第 4 章：创建产品目录：第二部分
- - '##'
  - 第 5 章：搜索商品目录
- - '##'
  - 第 6 章：使用 PayPal 接收付款
- - '##'
  - 第 7 章：商品目录管理
- - '#'
  - 第二部分 — 开发阶段二
- - '##'
  - 第 8 章：购物车
- - '##'
  - 第 9 章：处理客户订单
- - '##'
  - 第 10 章：产品推荐
- - '#'
  - 第三部分 — 开发阶段三
- - '##'
  - 第 11 章：管理客户信息
- - '##'
  - 第 12 章：存储客户订单
- - '##'
  - 第 13 章：实现订单管道：第一部分
- - '##'
  - 第 14 章：实现订单管道：第二部分
- - '##'
  - 第 15 章：信用卡交易
- - '##'
  - 第 16 章：产品评论
- - '##'
  - 第 17 章：连接到 Web 服务
- - '#'
  - 附录
- - '##'
  - 附录 A：安装 Apache、PHP 和 PostgreSQL
- - '##'
  - 附录 B：项目管理注意事项
- - '#'
  - 索引
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校者
- - '#'
  - 致谢
- - '#'
  - 引言
