name: The Definitive Guide to Shopify Themes
name_cn: Shopify 主题权威指南
slug: the-definitive-guide-to-shopify-themes
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '###'
  - 为何撰写本书？
- - '###'
  - 本书读者对象
- - '###'
  - 本书结构
- - '###'
  - 延伸阅读
- - '###'
  - 致谢
- - '##'
  - 第 1 章：Shopify 主题入门
- - '###'
  - Shopify 主题剖析
- - '####'
  - 主题结构
- - '###'
  - Liquid：Shopify 的模板语言
- - '###'
  - 资产文件
- - '###'
  - 使用 Shopify 主题
- - '####'
  - 设置开发商店
- - '####'
  - 总结
- - '##'
  - 第 2 章：工具与工作流程
- - '###'
  - 迁移至本地开发环境
- - '###'
  - 将更改同步到 Shopify
- - '####'
  - 介绍 Theme Kit
- - '####'
  - 使用 Theme Kit
- - '###'
  - 将主题纳入版本控制
- - '####'
  - 适用于 Shopify 主题的 Git 工作流
- - '#####'
  - 使用 Git 的主题功能分支
- - '###'
  - Slate 与主题构建工具
- - '####'
  - Grunt 和 Gulp：自动化任务运行器
- - '####'
  - 其他工作流自动化工具
- - '####'
  - 介绍 Slate
- - '###'
  - 总结
- - '##'
  - 第 3 章：原则与流程
- - '###'
  - 设计原则
- - '####'
  - 理解设计目标
- - '####'
  - 为人而设计
- - '####'
  - 针对不同场景的设计
- - '###'
  - 开发原则
- - '####'
  - 保持简单
- - '####'
  - 利用渐进增强
- - '###'
  - 文档化工作
- - '###'
  - 采用防御式与模块化编程
- - '###'
  - 流程原则
- - '####'
  - 客户与项目匹配度
- - '####'
  - 迭代开发与客户投入
- - '####'
  - 预期设定
- - '####'
  - 用户测试
- - '###'
  - 总结
- - '##'
  - 第 4 章：设计主题基础
- - '###'
  - 起点
- - '####'
  - 主题脚手架
- - '####'
  - 示例产品数据
- - '####'
  - 主题的布局
- - '###'
  - 设计布局与导航
- - '####'
  - 站点页眉
- - '#####'
  - 使页眉可配置
- - '####'
  - 导航菜单
- - '###'
  - 导航菜单设计
- - '###'
  - 下拉菜单设计指南
- - '####'
  - 大型菜单（Mega-Menus）
- - '####'
  - 网站页脚（The Site Footer）
- - '####'
  - 练习：布局与导航
- - '###'
  - 总结
- - '##'
  - 第 5 章：设计产品页面
- - '###'
  - 产品页面
- - '###'
  - 产品页面信息层级
- - '###'
  - 添加产品图片
- - '####'
  - 产品图片的设计考量
- - '####'
  - Shopify 的图片滤镜
- - '####'
  - 可缩放的产品图片与产品灯箱
- - '####'
  - 产品视频
- - '###'
  - 添加产品详情与“加入购物车”表单
- - '####'
  - 产品详情与描述
- - '####'
  - 添加到购物车表单
- - '###'
  - 添加推荐产品
- - '####'
  - 关联产品与替代产品
- - '####'
  - Shopify 上的推荐商品
- - '###'
  - 改进产品页面
- - '####'
  - 添加产品信息
- - '#####'
  - 使用元字段管理附加信息
- - '####'
  - 改善移动端体验
- - '####'
  - 创建备选页面模板
- - '###'
  - 总结
- - '##'
  - 第 6 章：设计主页和商品系列页面
- - '###'
  - 首页
- - '####'
  - 首页的设计目标
- - '#####'
  - 传达品牌定位
- - '#####'
  - 传达产品范围
- - '#####'
  - 清晰的下一步操作
- - '####'
  - 实现首页
- - '#####'
  - 上手首页分区
- - '#####'
  - 添加英雄图像部分
- - '###'
  - 产品系列页面
- - '####'
  - 商品集合页的设计目标
- - '####'
  - Shopify 商品集合页概念
- - '#####'
  - Shopify 中的分类
- - '#####'
  - 筛选
- - '#####'
  - 排序
- - '#####'
  - 分页
- - '#####'
  - 视图
- - '#####'
  - 整合所有要素
- - '####'
  - 实现商品集合页
- - '####'
  - 添加带分页的商品循环
- - '####'
  - 添加排序功能
- - '####'
  - 产品列表的不同呈现方式
- - '#####'
  - 为主题示例添加视图切换选项
- - '#####'
  - 添加类别级筛选
- - '####'
  - 添加基于标签的筛选功能
- - '####'
  - 渐进增强集合页面
- - '###'
  - 本章小结
- - '##'
  - 第 7 章：购物车、结账与内容
- - '###'
  - 购物车页面
- - '####'
  - 购物车页面的设计目标
- - '####'
  - 实现购物车页面
- - '#####'
  - 添加可编辑的购物车内容列表
- - '######'
  - 添加运费计算器
- - '#####'
  - 添加追加销售优惠
- - '###'
  - 结账流程
- - '####'
  - 使用 Shopify Plus 自定义结账流程
- - '#####'
  - 在结账流程中添加门店自提选择器
- - '###'
  - 内容页面
- - '###'
  - 总结
- - '###'
  - 脚注
- - '##'
  - 第 8 章：主题设置与全球化
- - '###'
  - 主题设置
- - '####'
  - 什么应该被设为设置项？
- - '#####'
  - 针对“单次使用”主题的设置
- - '#####'
  - 针对“多用途”主题的设置
- - '#####'
  - 针对“分发式”主题的设置
- - '####'
  - 主题设置指南
- - '####'
  - 在主题中使用设置
- - '#####'
  - 迭代模式
- - '#####'
  - 在预处理文件中使用设置
- - '#####'
  - 默认值过滤器
- - '###'
  - 走向全球化
- - '####'
  - i18n 与 l16n 的区别
- - '####'
  - 区域设置，而非语言
- - '####'
  - 为何本地化至关重要
- - '#####'
  - 获取流量
- - '#####'
  - 转化率
- - '#####'
  - 上级要求
- - '#####'
  - 实证需求
- - '####'
  - 要么不做，要么做好
- - '####'
  - Shopify 主题的局限性
- - '####'
  - 让主题可翻译
- - '#####'
  - 别忘了 JavaScript！
- - '####'
  - 向顾客展示多种货币
- - '###'
  - 本章小结
- - '##'
  - 第 9 章：SEO 与社交分享
- - '###'
  - 搜索引擎优化（SEO）
- - '####'
  - 站外优化与站内优化
- - '####'
  - 语义化 HTML
- - '####'
  - 关键词与内容
- - '###'
  - 关键词分析
- - '###'
  - 重复内容
- - '###'
  - 结构化数据
- - '####'
  - Schema.org 词汇表
- - '####'
  - 微数据
- - '#####'
  - 进入 JSON-LD
- - '###'
  - 社交分享
- - '####'
  - 开放图谱标记
- - '#####'
  - 添加开放图谱标记
- - '#####'
  - 测试开放图谱标记
- - '####'
  - 推特卡片标记
- - '#####'
  - 添加推特卡片标记
- - '#####'
  - 验证 Twitter 卡片标记
- - '####'
  - 重视分享
- - '#####'
  - 决定支持哪些分享选项
- - '#####'
  - 整合分享功能
- - '####'
  - 练习：SEO 与社交分享
- - '###'
  - 总结
- - '###'
  - 脚注
- - '##'
  - 第 10 章：性能优化
- - '###'
  - 为什么性能很重要
- - '###'
  - 为什么性能会被忽视
- - '###'
  - 性能分析与指标
- - '####'
  - 性能测量工具
- - '#####'
  - PageSpeed 见解（PageSpeed Insights）
- - '#####'
  - 雅虎 YSlow
- - '#####'
  - WebPageTest.org
- - '#####'
  - 该用哪个工具？
- - '####'
  - 主题性能指标
- - '#####'
  - 关键指标 1：页面重量
- - '#####'
  - 关键指标 2：HTTP 请求次数
- - '#####'
  - 关键指标 3：加载时间
- - '###'
  - 性能优化技术
- - '####'
  - 技巧一：简化页面
- - '####'
  - 技巧二：图片优化
- - '#####'
  - 图片优化基础
- - '#####'
  - 自动化图片优化
- - '#####'
  - 有损图片优化——突破极限
- - '####'
  - 技巧 3：资源合并
- - '#####'
  - 大型 JavaScript 库
- - '#####'
  - 使用主题设置的资源
- - '#####'
  - 仅用于特定页面的资源
- - '#####'
  - 自动合并
- - '#####'
  - 图片合并
- - '#####'
  - 未来发展
- - '####'
  - 技巧 4：资源压缩
- - '#####'
  - 如何压缩资源
- - '####'
  - 技巧 5：其他零碎事项
- - '#####'
  - 实现设备响应式设计
- - '#####'
  - 使用延迟加载
- - '#####'
  - 为垫片/回退方案使用条件加载
- - '#####'
  - 掌握“async”属性
- - '#####'
  - 检查资源 404 和 301 错误
- - '###'
  - 评估性能改进
- - '###'
  - 最后想法
- - '###'
  - 总结
- - '##'
  - 第 11 章：协作式主题开发
- - '###'
  - 关于主题协作
- - '####'
  - 使用版本控制的协作工作流程
- - '####'
  - 协作部署流程
- - '#####'
  - 克隆 Shopify 商店
- - '###'
  - Shopify 主题商店
- - '####'
  - 进入主题商店
- - '#####'
  - 熟悉流程
- - '#####'
  - 拥有新颖或独特的视角
- - '#####'
  - 与主题团队密切合作
- - '#####'
  - 遵循主题 Liquid 和内容指南
- - '#####'
  - 做好准备提供支持
- - '####'
  - 如果主题未获通过怎么办
- - '#####'
  - 单打独斗
- - '#####'
  - 使用替代的主题市场
- - '#####'
  - 框架化
- - '#####'
  - 使用开源策略
- - '###'
  - 利用 Shopify 生态系统
- - '###'
  - 去哪里参与
- - '####'
  - 官方 Shopify 渠道
- - '####'
  - 其他资源
- - '####'
  - 线下活动
- - '####'
  - 使用开源
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Y
- - '###'
  - Z
- - '##'
  - 关于作者与技术审校
