name: Make an E-commerce Site in a Weekend Using PHP
name_cn: PHP 周末电商网站构建指南
slug: make-an-e-commerce-site-in-a-weekend-using-php
toc:
- - '#'
  - 周末搭建电子商务网站：使用 PHP
- - '##'
  - 引言
- - '##'
  - 关键主题覆盖范围
- - '##'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 内容概览
- - '##'
  - 关于作者与技术审校者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '#'
  - 第1章 引言
- - '##'
  - 为什么选择 PHP？
- - '##'
  - 电子商务网站的外观
- - '###'
  - 开发网站所需的软件
- - '###'
  - 安装 WampServer
- - '##'
  - 安装 LAMP 服务器
- - '###'
  - 启动服务器
- - '###'
  - 配置 MySQL
- - '####'
  - 必需的数据库表
- - '####'
  - 运行 MySQL 脚本的步骤
- - '##'
  - 章节总结
- - '#'
  - 第2章 PHP 与 MySQL
- - '##'
  - 编写你的第一个 PHP 脚本
- - '###'
  - 在 PHP 中使用变量
- - '###'
  - echo 语句
- - '###'
  - 字符串拼接
- - '##'
  - 用于数据传输的 HTTP 方法
- - '###'
  - GET 方法
- - '###'
  - POST 方法
- - '##'
  - 在脚本之间传递信息
- - '###'
  - 使用 `$_GET` 数组
- - '###'
  - 使用 `$_POST` 数组
- - '###'
  - 使用 `$_REQUEST` 数组
- - '##'
  - 创建注册表单
- - '###'
  - 应用验证检查
- - '###'
  - 清单 2-11. JavaScript 文件 (checkform.js)
- - '###'
  - 连接 PHP 与 MySQL 的代码
- - '####'
  - 通过 PHP 执行 SQL 命令
- - '#####'
  - 在数据库表中存储信息
- - '#####'
  - 从数据库访问信息
- - '######'
  - '`mysqli_num_rows()`'
- - '######'
  - '`mysqli_affected_rows()`'
- - '######'
  - '`mysqli_fetch_array()`'
- - '######'
  - '`extract()`'
- - '##'
  - 实现身份验证
- - '##'
  - 本章小结
- - '#'
  - 第3章 使用 PHP 访问数据库
- - '##'
  - 访问产品并将其显示在屏幕上
- - '##'
  - 创建下拉菜单
- - '###'
  - CSS
- - '##'
  - 添加网站页眉
- - '##'
  - 实现搜索功能
- - '##'
  - 显示产品详情
- - '##'
  - 会话处理
- - '###'
  - 会话处理中使用的函数
- - '####'
  - '`session_start()`'
- - '####'
  - '`session_id()`'
- - '####'
  - '`isset()`'
- - '##'
  - 登录与登出
- - '##'
  - 定义网站主页
- - '##'
  - 本章小结
- - '#'
  - 第4章 管理购物车
- - '##'
  - 将选定商品保存到购物车
- - '###'
  - 维护购物车
- - '##'
  - 使用 AJAX 在站点页眉中显示购物车数量
- - '##'
  - 前往结账
- - '###'
  - 提供配送信息
- - '##'
  - 了解不同的支付模式
- - '##'
  - 进行支付
- - '###'
  - jQuery
- - '####'
  - 列表 4-7. `purchase.php` 脚本允许您输入支付方式和配送信息
- - '##'
  - 本章小结
- - '#'
  - 索引
