name: PHP objects, patterns, and practice
name_cn: PHP 对象、模式与实践指南
slug: php-objects-patterns-and-practice
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 第一部分
- - '#'
  - 1. PHP：设计与管理
- - '##'
  - 问题所在
- - '##'
  - PHP 与其他语言
- - '##'
  - 关于本书
- - '###'
  - 对象
- - '###'
  - 模式
- - '###'
  - 实践
- - '##'
  - 第五版新增内容
- - '##'
  - 总结
- - '#'
  - 2. PHP 与对象
- - '##'
  - PHP 对象的意外成功
- - '###'
  - 最初：PHP/FI
- - '###'
  - 语法糖：PHP 3
- - '###'
  - PHP 4 与悄然发生的革命
- - '###'
  - 拥抱变革：PHP 5
- - '###'
  - PHP 7：缩小差距
- - '##'
  - 倡导与不可知论：对象的争论
- - '##'
  - 小结
- - '#'
  - 3. 对象基础
- - '##'
  - 类和对象
- - '###'
  - 第一个类
- - '###'
  - 第一个（或两个）对象
- - '##'
  - 在类中设置属性
- - '##'
  - 使用方法
- - '###'
  - 创建构造方法
- - '##'
  - 参数与类型
- - '###'
  - 原始类型
- - '####'
  - 原始类型至关重要：一个示例
- - '###'
  - 善用提示：对象类型
- - '##'
  - 关于类类型声明的说明
- - '##'
  - 继承
- - '###'
  - 继承问题
- - '##'
  - 使用继承
- - '####'
  - 构造函数与继承
- - '####'
  - 调用被重写的方法
- - '###'
  - 公有、私有与受保护：管理类的访问权限
- - '###'
  - 访问器方法
- - '###'
  - ShopProduct 类
- - '##'
  - 总结
- - '#'
  - 4. 高级特性
- - '##'
  - 静态方法与属性
- - '##'
  - 常量属性
- - '##'
  - 抽象类
- - '##'
  - 接口
- - '##'
  - 特质
- - '###'
  - 特质要解决的问题
- - '###'
  - 定义和使用特质
- - '###'
  - 使用多个 Trait
- - '###'
  - 结合 Trait 和接口
- - '###'
  - 使用 `insteadof` 管理方法名冲突
- - '###'
  - 为被覆盖的 Trait 方法设置别名
- - '###'
  - 在 Trait 中使用静态方法
- - '###'
  - 访问宿主类的属性
- - '###'
  - 在 Trait 中定义抽象方法
- - '###'
  - 更改 Trait 方法的访问权限
- - '##'
  - 后期静态绑定：`static`关键字
- - '##'
  - 处理错误
- - '###'
  - 异常
- - '####'
  - 抛出异常
- - '####'
  - 异常类的子类化
- - '###'
  - 使用 finally 处理 try/catch 之后的清理工作
- - '###'
  - final 类和方法
- - '##'
  - 内部错误类
- - '##'
  - 使用拦截器
- - '##'
  - 定义析构函数方法
- - '##'
  - 使用 `__clone()` 复制对象
- - '##'
  - 为对象定义字符串值
- - '##'
  - 回调、匿名函数和闭包
- - '##'
  - 匿名类
- - '#'
  - 总结
- - '#'
  - 5. 对象工具
- - '##'
  - PHP 与包
- - '###'
  - PHP 包与命名空间
- - '####'
  - 命名空间的救赎
- - '###'
  - 使用文件系统模拟包
- - '###'
  - PEAR 风格的命名
- - '####'
  - 包含路径
- - '###'
  - 自动加载
- - '##'
  - 类与对象函数
- - '###'
  - 查找类
- - '###'
  - 了解对象或类
- - '###'
  - 获取类的完全限定字符串引用
- - '###'
  - 了解方法
- - '###'
  - 了解属性
- - '###'
  - 了解继承
- - '###'
  - 方法调用
- - '##'
  - 反射 API
- - '###'
  - 入门指南
- - '###'
  - 是时候撸起袖子大干一场了
- - '###'
  - 检查一个类
- - '###'
  - 检查方法
- - '###'
  - 检查方法参数
- - '###'
  - 使用反射 API
- - '#'
  - 摘要
- - '#'
  - 第 6 章 对象与设计
- - '##'
  - 定义代码设计
- - '##'
  - 面向对象与过程式编程
- - '###'
  - 职责
- - '###'
  - 内聚性
- - '###'
  - 耦合性
- - '###'
  - 正交性
- - '###'
  - 选择你的类
- - '###'
  - 多态性
- - '##'
  - 封装
- - '##'
  - 忘记如何实现
- - '##'
  - 四个路标
- - '###'
  - 代码重复
- - '###'
  - 知道太多的类
- - '###'
  - 万事通
- - '##'
  - 条件语句
- - '##'
  - UML
- - '###'
  - 类图
- - '####'
  - 表示类
- - '####'
  - 属性
- - '####'
  - 操作
- - '####'
  - 描述继承与实现
- - '#####'
  - 关联
- - '#####'
  - 聚合与组合
- - '#####'
  - 描述使用关系
- - '#####'
  - 使用注释
- - '###'
  - 顺序图
- - '##'
  - 总结
- - '#'
  - 第二部分：设计模式
- - '#'
  - 7. 什么是设计模式？为何使用它们？
- - '##'
  - 什么是设计模式？
- - '###'
  - 设计模式概览
- - '####'
  - 命名
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '####'
  - 后果
- - '##'
  - 四人帮（Gang of Four）格式
- - '##'
  - 为什么使用设计模式？
- - '###'
  - 设计模式定义一个问题
- - '###'
  - 设计模式定义一个解决方案
- - '###'
  - 设计模式与语言无关
- - '###'
  - 模式定义了一种词汇表
- - '###'
  - 模式是经过考验的
- - '###'
  - 模式是为协作而设计的
- - '###'
  - 设计模式提升良好设计
- - '###'
  - 设计模式被流行框架所使用
- - '##'
  - PHP 与设计模式
- - '##'
  - 总结
- - '#'
  - 8. 一些模式原则
- - '##'
  - 模式启示录
- - '###'
  - 组合与继承
- - '####'
  - 问题所在
- - '####'
  - 使用组合
- - '##'
  - 解耦
- - '###'
  - 问题
- - '###'
  - 降低耦合度
- - '##'
  - 面向接口编程，而非面向实现编程
- - '##'
  - 变化的概念
- - '##'
  - 模式病
- - '##'
  - 这些模式
- - '###'
  - 生成对象的模式
- - '###'
  - 组织对象和类的模式
- - '###'
  - 面向任务的模式
- - '###'
  - 企业模式
- - '###'
  - 数据库模式
- - '##'
  - 总结
- - '#'
  - 9. 生成对象
- - '##'
  - 对象生成中的问题与解决方案
- - '##'
  - 单例模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 结果
- - '##'
  - 工厂方法模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 后果
- - '##'
  - 抽象工厂模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 后果
- - '##'
  - 原型模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '##'
  - 推向极致：服务定位器
- - '##'
  - 辉煌的隔离：依赖注入
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 后果
- - '##'
  - 总结
- - '#'
  - 10. 灵活对象编程的模式
- - '##'
  - 组织类以实现灵活的对象
- - '##'
  - 组合模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 后果
- - '###'
  - 组合模式小结
- - '##'
  - 装饰器模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 结果
- - '##'
  - 外观模式
- - '###'
  - 问题所在
- - '###'
  - 实现
- - '###'
  - 影响
- - '##'
  - 总结
- - '#'
  - 11. 执行与表达任务
- - '##'
  - 解释器模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 解释器模式问题
- - '##'
  - 策略模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '##'
  - 观察者模式
- - '###'
  - 实现
- - '##'
  - Visitor 模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 访问者模式的问题
- - '##'
  - 命令模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '##'
  - Null Object 模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '##'
  - 总结
- - '#'
  - 12. 企业模式
- - '##'
  - 架构概述
- - '###'
  - 诸模式
- - '##'
  - 应用与分层
- - '##'
  - 我们在开始之前偷个懒
- - '###'
  - 注册表（Registry）
- - '####'
  - 问题
- - '####'
  - 实现
- - '###'
  - 注册表、作用域与 PHP
- - '###'
  - 影响
- - '##'
  - 表示层
- - '###'
  - 前端控制器
- - '####'
  - 问题所在
- - '####'
  - 实现
- - '#####'
  - ApplicationHelper
- - '#####'
  - '`CommandResolver`'
- - '#####'
  - '`Request`'
- - '#####'
  - 一个命令
- - '#####'
  - 概述
- - '####'
  - 影响
- - '###'
  - 应用程序控制器
- - '####'
  - 问题
- - '####'
  - 实现
- - '#####'
  - 前端控制器
- - '#####'
  - 实现概述
- - '#####'
  - 配置文件
- - '#####'
  - 解析配置文件
- - '##'
  - 管理组件数据
- - '###'
  - '`Command`类'
- - '###'
  - 具体命令示例
- - '###'
  - 影响与后果
- - '##'
  - 页面控制器
- - '###'
  - 问题所在
- - '####'
  - 实现
- - '####'
  - 后果
- - '###'
  - 模板视图与视图助手
- - '####'
  - 问题
- - '####'
  - 实现
- - '##'
  - 结果
- - '##'
  - 业务逻辑层
- - '###'
  - 事务脚本
- - '####'
  - 问题
- - '####'
  - 实现
- - '####'
  - 结论
- - '###'
  - 领域模型
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 结果
- - '###'
  - 总结
- - '#'
  - 13. 数据库模式
- - '##'
  - 数据层
- - '##'
  - 数据映射器
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 处理多行数据
- - '###'
  - 使用生成器替代迭代器接口
- - '###'
  - 获取集合对象
- - '###'
  - 后果
- - '##'
  - 身份映射
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 后果
- - '##'
  - 工作单元
- - '###'
  - 问题所在
- - '###'
  - 实现
- - '###'
  - 结果
- - '###'
  - 延迟加载
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 影响
- - '##'
  - 领域对象工厂
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 影响
- - '##'
  - 标识对象
- - '###'
  - 问题
- - '###'
  - 实现
- - '##'
  - 创建标识对象与查询工厂
- - '###'
  - 影响
- - '##'
  - 选择工厂与更新工厂模式
- - '###'
  - 问题
- - '###'
  - 实现
- - '###'
  - 影响
- - '##'
  - 数据映射器还剩下什么？
- - '##'
  - 摘要
- - '#'
  - 第三部分 实践
- - '#'
  - 14. 好（与坏）实践
- - '##'
  - 超越代码
- - '##'
  - 借用轮子
- - '##'
  - 和睦共处
- - '##'
  - 为你的代码插上翅膀
- - '##'
  - 标准
- - '##'
  - Vagrant
- - '##'
  - 测试
- - '##'
  - 持续集成
- - '##'
  - 总结
- - '#'
  - 15. PHP 标准
- - '##'
  - 为什么需要标准？
- - '##'
  - 什么是 PHP 标准建议？
- - '###'
  - 为什么特别选择 PSR？
- - '###'
  - PSR 为谁而设计？
- - '##'
  - 代码风格
- - '###'
  - PSR-1 基本编码标准
- - '####'
  - 开始与结束标签
- - '####'
  - 副作用
- - '####'
  - 命名
- - '##'
  - 更多规则与示例
- - '###'
  - PSR-2 编码风格指南
- - '####'
  - PHP 文档的开头与结尾
- - '####'
  - 类的开始与结束
- - '####'
  - 属性声明
- - '####'
  - 方法的开始与结束
- - '#####'
  - 单行声明
- - '#####'
  - 多行声明
- - '####'
  - 行与缩进
- - '####'
  - 方法调用与函数调用
- - '####'
  - 控制流
- - '###'
  - 检查与修复你的代码
- - '##'
  - PSR-4 自动加载
- - '###'
  - 对我们来说重要的规则
- - '#'
  - 总结
- - '##'
  - 16. PHP 使用和创建组件
- - '###'
  - 使用 Composer
- - '##'
  - 什么是 Composer？
- - '##'
  - 安装 Composer
- - '##'
  - 安装一个（一组）包
- - '##'
  - 从命令行安装包
- - '###'
  - '`require-dev`'
- - '###'
  - Composer 和自动加载
- - '###'
  - 创建你自己的包
- - '####'
  - 添加包信息
- - '##'
  - 平台包
- - '##'
  - 通过 Packagist 分发
- - '###'
  - 保持私有
- - '##'
  - 总结
- - '#'
  - 17. 使用 Git 进行版本控制
- - '##'
  - 为什么使用版本控制？
- - '##'
  - 如果还没体验过，版本控制将改变你的人生
- - '##'
  - 获取 Git
- - '##'
  - 使用在线 Git 仓库
- - '##'
  - 配置 Git 服务器
- - '###'
  - 创建远程仓库
- - '##'
  - 创建 Git 仓库
- - '###'
  - 为本地用户准备仓库
- - '###'
  - 为用户提供访问权限
- - '##'
  - 创建 `authorized_keys` 文件并粘贴用户的公钥
- - '###'
  - 关闭 `git` 用户的 Shell 访问
- - '##'
  - 开始一个项目
- - '##'
  - 克隆仓库
- - '##'
  - 更新与提交
- - '##'
  - 添加和删除文件与目录
- - '###'
  - 添加文件
- - '###'
  - 删除文件
- - '###'
  - 添加目录
- - '###'
  - 删除目录
- - '##'
  - 标记发布版本
- - '##'
  - 分支项目
- - '##'
  - 总结
- - '#'
  - 18. 使用 PHPUnit 进行测试
- - '##'
  - 功能测试和单元测试
- - '##'
  - 手动测试
- - '###'
  - 每个 Vagrant 开发环境都需要一个 box。你可以在 https://atlas.hashicorp.com/search 上搜索 box。
- - '##'
  - 将本地目录挂载到 Vagrant Box 上
- - '##'
  - 配置（Provisioning）
- - '##'
  - 设置 Web 服务器
- - '##'
  - 设置 MySQL
- - '###'
  - install data here if needed
- - '##'
  - 大量输出
- - '##'
  - 配置主机名
- - '##'
  - 总结
- - '##'
  - 小结
- - '##'
  - 21. 持续集成
- - '###'
  - 什么是持续集成？
- - '##'
  - 为项目准备 CI
- - '##'
  - CI 与版本控制
- - '##'
  - Phing
- - '##'
  - 单元测试
- - '##'
  - 文档
- - '##'
  - 代码覆盖率
- - '##'
  - Git 插件
- - '##'
  - xUnit 插件
- - '##'
  - Phing 插件
- - '##'
  - Clover PHP 插件
- - '##'
  - HTML Publisher 插件
- - '##'
  - Checkstyle 插件
- - '##'
  - 设置 Git 公钥
- - '##'
  - 安装项目
- - '##'
  - 运行首次构建
- - '##'
  - 配置报告
- - '###'
  - 触发构建
- - '###'
  - 测试失败
- - '###'
  - 总结
- - '##'
  - 22. 对象、模式、实践
- - '###'
  - 对象
- - '####'
  - 选择
- - '####'
  - 封装与委托
- - '####'
  - 解耦
- - '##'
  - 解耦
- - '##'
  - 可重用性
- - '##'
  - 美学
- - '##'
  - 模式
- - '###'
  - 模式带给我们的好处
- - '####'
  - 经过验证的
- - '####'
  - 模式暗示其他模式
- - '##'
  - 模式与设计原则
- - '###'
  - 通用词汇表
- - '###'
  - 模式推动设计
- - '###'
  - 模式与设计原则
- - '####'
  - 优先使用组合而非继承
- - '####'
  - 避免紧密耦合
- - '####'
  - 针对接口编程，而非实现
- - '####'
  - 封装变化的概念
- - '##'
  - 实践
- - '###'
  - 文档、构建、测试与版本控制
- - '##'
  - 测试
- - '##'
  - 标准
- - '##'
  - 版本控制
- - '##'
  - 自动化构建
- - '##'
  - 持续集成
- - '##'
  - 我遗漏的内容
- - '##'
  - 总结
- - '##'
  - 23. 附录 A：参考书目
- - '###'
  - 书籍
- - '##'
  - 文章
- - '##'
  - 网站
- - '##'
  - 附录 B：一个简单的解析器
- - '###'
  - 扫描器
- - '##'
  - 解析器
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - '`getFromMap()` 方法'
- - '###'
  - Git 服务器
- - '###'
  - '`globalKey()` 方法'
- - '###'
  - H
- - '###'
  - I
- - '###'
  - 标识映射
- - '###'
  - 继承
- - '###'
  - '`init()` 方法'
- - '###'
  - 解释器模式
- - '###'
  - '`is_array()` 函数'
- - '###'
  - J, K
- - '###'
  - L
- - '###'
  - 后期静态绑定
- - '###'
  - '`LiteralExpression` 类'
- - '###'
  - M
- - '###'
  - '`Megaquiz` 项目'
- - '###'
  - N
- - '###'
  - 空对象模式
- - '###'
  - O
- - '###'
  - 对象生成
- - '###'
  - 原型对象
- - '###'
  - 原型模式
- - '###'
  - 优势
- - '###'
  - 文明风格网页游戏
- - '###'
  - 类图
- - '###'
  - '`clone()` 方法'
- - '###'
  - '`$navigability` 属性'
- - '###'
  - 并行继承层次结构
- - '###'
  - '`TerrainFactory` 对象'
- - '###'
  - '`TerrainFactory` 类'
- - '###'
  - 单例模式
- - '###'
  - 后果
- - '###'
  - DSN 字符串
- - '###'
  - 全局变量
- - '###'
  - 实现
- - '###'
  - '`$instance` 属性'
- - '###'
  - '`Preferences` 类'
- - '###'
  - '`Preferences` 对象'
- - '###'
  - 私有构造函数
- - '###'
  - 静态方法
- - '###'
  - 设计良好的系统
- - '###'
  - 字符串与实例化
- - '###'
  - 面向对象设计
- - '###'
  - 美学的考量
- - '###'
  - 自动构建
- - '###'
  - 代码重复
- - '###'
  - 持续集成（CI）
- - '###'
  - 解耦的定义
- - '###'
  - 封装
- - '###'
  - 全局变量
- - '###'
  - 元系统
- - '###'
  - 多个项目
- - '###'
  - phpDocumentor
- - '###'
  - 多态
- - '###'
  - 公共接口
- - '###'
  - 促进可复用性
- - '###'
  - 测试框架的优势
- - '###'
  - 紧耦合的原因
- - '###'
  - 面向对象系统
- - '###'
  - 对象与设计
- - '###'
  - 抽象基类
- - '###'
  - '`addParam()` 方法'
- - '###'
  - 类
- - '###'
  - 代码设计
- - '###'
  - 内聚性
- - '###'
  - 耦合
- - '###'
  - 封装
- - '###'
  - 文件扩展名
- - '###'
  - '`getInstance()` 方法'
- - '###'
  - 示例代码
- - '###'
  - 接口
- - '###'
  - 正交性
- - '###'
  - 持久化方法
- - '###'
  - 多态
- - '###'
  - 抽象基类
- - '###'
  - 条件语句
- - '###'
  - 定义
- - '###'
  - 返回类型
- - '###'
  - 子类
- - '###'
  - 过程式代码
- - '###'
  - '`readParams` 函数'
- - '###'
  - 职责
- - '###'
  - 路标
- - '###'
  - 代码重复
- - '###'
  - 条件语句
- - '###'
  - 全局变量
- - '###'
  - 职责
- - '###'
  - 静态方法
- - '###'
  - UML
- - '###'
  - '`writeParams()` 函数'
- - '###'
  - XML 模式
- - '###'
  - '`$objects` 数组'
- - '###'
  - 对象工具与技术
- - '###'
  - 自动加载
- - '###'
  - 默认行为
- - '###'
  - 函数
- - '###'
  - 机制
- - '###'
  - '`replaceUnderscores()` 函数'
- - '###'
  - '`ShopProduct` 类'
- - '###'
  - '`spl_autoload()` 函数'
- - '###'
  - '`spl_register_function()`'
- - '###'
  - '`spl_unregister_function()`'
- - '###'
  - 类与对象函数
- - '###'
  - '`BookProduct`/`CdProduct` 类'
- - '###'
  - '`callable()`'
- - '###'
  - '`class_exists()` 函数'
- - '###'
  - 完全限定字符串引用
- - '###'
  - '`get_class()` 函数'
- - '###'
  - '`get_class_methods()`'
- - '###'
  - '`get_declared_classes()` 函数'
- - '###'
  - '`getProduct()` 函数'
- - '###'
  - 继承
- - '###'
  - '`method_exists()` 函数'
- - '###'
  - 方法调用
- - '###'
  - 属性
- - '###'
  - 文件系统
- - '###'
  - 包含路径
- - '###'
  - PEAR 方式
- - '###'
  - PHP 包与命名空间
- - '###'
  - 显式别名
- - '###'
  - 反斜杠访问
- - '###'
  - 类、函数与变量
- - '###'
  - '`Debug` 类'
- - '###'
  - 全局空间
- - '###'
  - '`helloWorld()`'
- - '###'
  - '`__NAMESPACE__` 常量'
- - '###'
  - 命名冲突
- - '###'
  - 组织/项目标识符
- - '###'
  - URL 与文件路径
- - '###'
  - 反射 API
- - '###'
  - 应用程序
- - '###'
  - 类
- - '###'
  - 可克隆方法
- - '###'
  - 检查方法
- - '###'
  - '`execute()` 方法'
- - '###'
  - '`handleMethod()`'
- - '###'
  - 实现
- - '###'
  - '`init()` 方法循环'
- - '###'
  - 模块接口
- - '###'
  - 模块对象的 setter 方法
- - '###'
  - 多维数组
- - '###'
  - '`$params` 数组参数'
- - '###'
  - 快速但不优雅的方法
- - '###'
  - '`ReflectionClass`'
- - '###'
  - '`ReflectionClass` 对象'
- - '###'
  - '`ReflectionFunction` 类'
- - '###'
  - '`ReflectionMethod`'
- - '###'
  - 静态 `export()` 方法
- - '###'
  - '`var_dump()` 函数'
- - '###'
  - 观察者模式
- - '###'
  - 抽象超类
- - '###'
  - '`attach()` 方法'
- - '###'
  - 类图
- - '###'
  - '`detach()` 方法'
- - '###'
  - '`getStatus()` 方法'
- - '###'
  - '`handleLogin()` 方法'
- - '###'
  - 实现
- - '###'
  - '`Login` 类'
- - '###'
  - '`LoginObserver` 类'
- - '###'
  - '`notify()` 方法'
- - '###'
  - '`Observer` 类接口'
- - '###'
  - '`rand()` 函数'
- - '###'
  - SPL
- - '###'
  - '`SplObjectStorage`'
- - '###'
  - '`SplObserver`'
- - '###'
  - '`SplSubject`'
- - '###'
  - '`Update()` 方法'
- - '###'
  - 用户访问
- - '###'
  - '`OperatorExpression`'
- - '###'
  - 正交性
- - '###'
  - 重载
- - '###'
  - P, Q
- - '###'
  - 包
- - '###'
  - 构建工具
- - '###'
  - 客户端与开发者
- - '###'
  - 云产品
- - '###'
  - Composer
- - '###'
  - 良好的 `mail()` 函数
- - '###'
  - Packagist 网站
- - '###'
  - PEAR
- - '###'
  - Phing 应用程序
- - '###'
  - 标准
- - '###'
  - 第三方包
- - '###'
  - 版本控制系统
- - '###'
  - '`ParamHandler` 类'
- - '###'
  - '`parse()` 方法'
- - '###'
  - 模式语言
- - '###'
  - '`PatternSet`'
- - '###'
  - 属性
- - '###'
  - '`exc_test`'
- - '###'
  - '`inc_code`'
- - '###'
  - '`refid` 属性'
- - '###'
  - PEAR
- - '###'
  - Pear 应用程序
- - '###'
  - '`performOperations()` 方法'
- - '###'
  - Phing
- - '###'
  - Ant
- - '###'
  - 定义
- - '###'
  - 安装工具
- - '###'
  - 包创建
- - '###'
  - PHP 应用程序
- - '###'
  - PHP 工具
- - '###'
  - tar/gzip 压缩包
- - '###'
  - 任务
- - '###'
  - PHP
- - '###'
  - 客户端代码
- - '###'
  - Zend Engine 2
- - '###'
  - PHP 5
- - '###'
  - PHP 代码库
- - '###'
  - Apache 模块 ModRewrite
- - '###'
  - BinaryCloud
- - '###'
  - 设计模式
- - '###'
  - Java 语言
- - '###'
  - 面向对象设计
- - '###'
  - 对象
- - '###'
  - 模式
- - '###'
  - 实践
- - '###'
  - 表示层
- - '###'
  - 测试
- - '###'
  - XP 原则
- - '###'
  - Zend 2 引擎
- - '###'
  - '`php_codesniffer` 任务'
- - '###'
  - PHP 扩展与应用库（PEAR）
- - '###'
  - PHP 框架互操作小组（PHP-Fig）
- - '###'
  - PHP 对象
- - '###'
  - 倡导与不可知论
- - '###'
  - Andi Gutmans
- - '###'
  - 拥抱变化
- - '###'
  - 特性
- - '###'
  - 继承
- - '###'
  - PHP 7
- - '###'
  - PHP/FI
- - '###'
  - 悄然革命
- - '###'
  - Zeev Suraski
- - '###'
  - PHP 的核心面向对象特性
- - '###'
  - 抽象类
- - '###'
  - 匿名类
- - '###'
  - 参数与类型
- - '###'
  - '`AddressManager` 类'
- - '###'
  - 类型提示
- - '###'
  - '`outputAddresses()` 方法'
- - '###'
  - 原始类型与检查函数
- - '###'
  - 内置错误类
- - '###'
  - 回调、匿名函数与闭包
- - '###'
  - 类
- - '###'
  - '`__clone()`'
- - '###'
  - 常量属性
- - '###'
  - 析构方法
- - '###'
  - final 类与方法
- - '###'
  - 错误处理
- - '###'
  - '`Conf` 类'
- - '###'
  - 错误标志
- - '###'
  - 异常
- - '###'
  - '`simplexml:load_file()`'
- - '###'
  - 子类化异常
- - '###'
  - 抛出异常
- - '###'
  - try/catch 子句
- - '###'
  - 继承
- - '###'
  - 拦截器方法
- - '###'
  - '`Address::$streetaddress` 属性'
- - '###'
  - '`__call()` 方法'
- - '###'
  - composite property
- - '###'
  - 表示层
- - '###'
  - 前端控制器
- - '###'
  - 页面控制器
- - '###'
  - 模板视图
- - '###'
  - 原型模式
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - 版本控制
- - '###'
  - 访问者模式
- - '###'
  - W
- - '###'
  - X, Y
- - '###'
  - Z
