name: PHP 8 for absolute beginners
name_cn: PHP 8 初学者指南
slug: php-8-for-absolute-beginners
toc:
- - '#'
  - 引言
- - '##'
  - 本书适合谁阅读
- - '##'
  - 如何阅读本书
- - '##'
  - 源代码
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 第一部分
- - '##'
  - 1. 编程准备工作
- - '###'
  - 目标
- - '###'
  - 为什么要从 PHP 开始？
- - '###'
  - 搭建开发环境
- - '####'
  - 什么是 PHP？PHP 是如何工作的？
- - '#####'
  - Apache 及其功能
- - '#####'
  - 使用 MySQL/MariaDB 存储信息
- - '####'
  - 安装 PHP、Apache 和 MySQL/MariaDB
- - '#####'
  - 安装 XAMPP
- - '#####'
  - 步骤 1：下载 XAMPP
- - '#####'
  - 步骤 2：按照说明进行操作
- - '#####'
  - 步骤 3：测试 XAMPP 以确保正确安装
- - '#####'
  - 打开 XAMPP 控制面板
- - '#####'
  - 如果 Apache 无法运行怎么办？
- - '#####'
  - 验证 Apache 和 PHP 是否在运行
- - '###'
  - 选择 PHP 编辑器
- - '###'
  - 创建你的第一个 PHP 程序
- - '###'
  - 运行你的第一个 PHP 脚本
- - '###'
  - 总结
- - '###'
  - 项目
- - '#'
  - 2. 理解 PHP：语言基础
- - '##'
  - 目标
- - '##'
  - 嵌入 PHP 脚本
- - '###'
  - 程序设计与逻辑
- - '###'
  - 使用 `echo`
- - '###'
  - 什么是变量？
- - '####'
  - 在变量中存储值
- - '####'
  - 变量是一个占位符
- - '####'
  - 有效的 PHP 变量名
- - '###'
  - 显示 PHP 错误
- - '###'
  - 安全编程
- - '##'
  - 使用 PHP 创建 HTML5 页面
- - '###'
  - HTML 回顾
- - '###'
  - 包含简单的页面模板
- - '###'
  - 包含模板
- - '###'
  - 安全编程
- - '###'
  - 注释你的代码
- - '####'
  - 块注释与单行注释
- - '####'
  - 避免命名冲突
- - '####'
  - 对象运算符
- - '####'
  - 使用 `StdClass` 对象处理页面数据
- - '####'
  - 页面视图
- - '##'
  - 文档排版
- - '###'
  - HTML 回顾
- - '###'
  - 制作动态网站导航
- - '####'
  - HTML 回顾
- - '###'
  - 使用 PHP 传递信息
- - '####'
  - 访问 URL 变量
- - '####'
  - 使用 `isset()` 测试变量是否已设置
- - '####'
  - 安全编程
- - '##'
  - 排版后的文档
- - '###'
  - '`$_GET`，一个超全局数组'
- - '###'
  - 动态包含页面视图
- - '###'
  - 严格的命名约定
- - '###'
  - 显示默认页面
- - '###'
  - 保护程序安全
- - '##'
  - 操作步骤说明
- - '###'
  - 排版后的文本
- - '###'
  - 验证 HTML
- - '###'
  - 使用 CSS 美化网站
- - '####'
  - CSS 回顾
- - '###'
  - 声明 `Page_Data` 类
- - '##'
  - 类生成对象
- - '###'
  - 使用动态样式规则高亮当前导航项
- - '###'
  - 总结
- - '###'
  - 项目
- - '#'
  - 3. 表单管理
- - '##'
  - 目标
- - '##'
  - 什么是表单？
- - '##'
  - 建立新的 PHP 项目
- - '###'
  - 亲自查看
- - '###'
  - 创建动态导航
- - '###'
  - 为表单创建页面视图
- - '###'
  - 在索引页面上显示页面视图
- - '###'
  - 程序设计及逻辑
- - '###'
  - 一个简单的搜索表单
- - '##'
  - '`<input>` 元素及常见类型'
- - '##'
  - 理解 `method` 属性
- - '##'
  - 命名 PHP 函数
- - '###'
  - 程序设计与逻辑
- - '###'
  - 命名函数的基本语法
- - '####'
  - 程序设计与逻辑
- - '####'
  - 程序设计与逻辑
- - '###'
  - 使用函数参数提高灵活性
- - '####'
  - 为测验创建表单
- - '#####'
  - HTML 回顾
- - '##'
  - 显示测验表单
- - '###'
  - POST 方法
- - '####'
  - 安全编程
- - '####'
  - 使用 `$_POST` 超全局变量
- - '####'
  - 程序设计逻辑
- - '###'
  - '`$_POST` 是一个数组'
- - '##'
  - 安全编程
- - '###'
  - 柯利定律：只做一件事
- - '##'
  - 程序设计逻辑
- - '##'
  - 代码即诗
- - '##'
  - 面向对象编程：使用构造函数、Getter 和 Setter
- - '##'
  - 安全编程
- - '##'
  - 注意
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 4. 构建动态图像画廊
- - '##'
  - 目标
- - '##'
  - 设置动态网站
- - '##'
  - 先决条件：一个包含一些图像的文件夹
- - '##'
  - 版权法
- - '##'
  - 创建导航
- - '###'
  - 创建导航项
- - '###'
  - 创建两个虚拟页面视图文件
- - '###'
  - 创建索引文件
- - '###'
  - 测试时间
- - '###'
  - 准备用于显示图片的函数
- - '##'
  - 迭代
- - '###'
  - While 循环
- - '###'
  - For 循环
- - '###'
  - 使用 glob 查找文件夹中的文件
- - '####'
  - For Each 循环
- - '###'
  - 显示所有图片
- - '###'
  - 注意事项
- - '###'
  - '`php.ini`'
- - '###'
  - '`$_FILES`'
- - '###'
  - 安全编程
- - '###'
  - 使用 PHP 上传文件
- - '##'
  - 规划上传器类
- - '###'
  - UML
- - '###'
  - 上传器类需求
- - '###'
  - 魔术方法 `__construct()`
- - '###'
  - 保存上传的文件
- - '###'
  - 使用上传器类
- - '##'
  - 单一职责原则
- - '##'
  - 总结
- - '##'
  - 项目
- - '#'
  - 5. PHP 基础回顾
- - '##'
  - 目标
- - '###'
  - 从头开始
- - '###'
  - 注释
- - '##'
  - PHP 函数
- - '##'
  - 变量
- - '##'
  - 条件语句
- - '##'
  - 逻辑运算符
- - '###'
  - L-1
- - '###'
  - L-2
- - '###'
  - L-3
- - '###'
  - L-4
- - '##'
  - 让我们看一些无效的比较及其产生的错误消息。
- - '###'
  - E-1
- - '###'
  - E-2
- - '###'
  - E-3
- - '###'
  - E-4
- - '###'
  - E-5
- - '##'
  - '`switch` 语句'
- - '##'
  - 函数
- - '###'
  - F-1
- - '###'
  - F-2
- - '###'
  - F-3
- - '###'
  - F-4
- - '##'
  - 数组
- - '##'
  - 循环
- - '#'
  - PHP 数组与枚举
- - '##'
  - 枚举
- - '##'
  - 总结
- - '##'
  - 项目
- - '#'
  - 第二部分
- - '#'
  - 6. 数据库、MVC 与数据对象
- - '##'
  - 目标
- - '##'
  - 使用模型-视图-控制器方法组织 PHP 脚本
- - '##'
  - 创建和使用 PHP 数据对象
- - '##'
  - MySQL/MariaDB 数据存储基础
- - '##'
  - 使用 SQL 操作数据
- - '##'
  - 为投票功能开发数据库
- - '###'
  - 使用 `CREATE` 构建数据库
- - '###'
  - '`CREATE TABLE` 语句'
- - '####'
  - 安全编程
- - '###'
  - 理解主键（PRIMARY KEY）
- - '###'
  - 理解自增（AUTO_INCREMENT）
- - '###'
  - INSERT 语句
- - '###'
  - SELECT 语句
- - '####'
  - 安全编程
- - '###'
  - UPDATE 语句
- - '####'
  - 安全编程
- - '##'
  - 编写数据库驱动型站点投票功能
- - '##'
  - 使用 MVC 分离关注点
- - '##'
  - 规划逻辑
- - '##'
  - 创建投票项目
- - '###'
  - PHP/MySQL 网站投票示例
- - '####'
  - 创建投票控制器
- - '####'
  - 创建投票模型
- - '####'
  - 创建投票视图
- - '####'
  - 连接投票视图与投票模型
- - '####'
  - 从 PHP 连接到 MySQL/MariaDB
- - '#####'
  - PHP 数据对象 (PDO)
- - '#####'
  - 打开连接
- - '##'
  - 排版后的文档
- - '###'
  - 与 Poll 模型共享数据库连接
- - '###'
  - 使用 PDOStatement 检索数据
- - '###'
  - 显示轮询表单
- - '##'
  - 根据表单输入更新数据库表
- - '###'
  - 安全编程
- - '##'
  - 响应用户输入
- - '##'
  - 总结
- - '##'
  - 项目
- - '#'
  - 7. 构建基本博客系统
- - '##'
  - 目标
- - '###'
  - 创建 blog_entry 数据库表
- - '##'
  - 数据库表单设计
- - '##'
  - 规划 PHP 脚本
- - '##'
  - 管理视图：创建管理博客站点
- - '###'
  - 创建管理员条目管理器导航
- - '###'
  - 窗口与导航
- - '###'
  - 加载管理员模块控制器
- - '###'
  - 创建管理员条目输入表单
- - '###'
  - 样式化管理员编辑器
- - '##'
  - 连接数据库
- - '###'
  - database.php
- - '##'
  - 使用设计模式
- - '###'
  - 表数据网关设计模式
- - '##'
  - 编写`Blog_Entry_Table`类
- - '###'
  - 安全编程
- - '##'
  - 处理管理表单输入并保存条目
- - '###'
  - newesteditor.php
- - '##'
  - 用户视图：获取所有博客条目的数据
- - '###'
  - 使用 SQL SUBSTRING 子句
- - '###'
  - 使用 SQL 别名
- - '##'
  - 为所有博客条目准备用户视图
- - '##'
  - 连接用户视图和用户模型
- - '##'
  - 响应用户的“阅读更多”请求
- - '##'
  - 获取条目数据
- - '###'
  - 安全编程
- - '##'
  - 创建博客视图
- - '##'
  - 显示条目
- - '###'
  - 代码异味：重复代码
- - '###'
  - 遵循 Curly 法则保持 DRY
- - '###'
  - 使用 Curly 法则进行重构
- - '##'
  - 安全编程
- - '##'
  - 总结
- - '##'
  - 项目
- - '#'
  - 8. 基础博客：条目与评论
- - '##'
  - 目标
- - '##'
  - 为管理员模块创建模型
- - '##'
  - 排版后的文档
- - '###'
  - 显示管理链接
- - '###'
  - 用待编辑的条目填充表单
- - '###'
  - 处理条目删除
- - '####'
  - 从数据库中删除条目
- - '###'
  - 响应删除请求
- - '###'
  - 准备模型以更新数据库中的条目
- - '###'
  - 控制器：插入还是更新？
- - '###'
  - 安全编程
- - '###'
  - 强制要求输入标题
- - '##'
  - 用户视图：构建和显示评论输入表单
- - '###'
  - 组合视图
- - '###'
  - 在数据库中创建评论表
- - '###'
  - 使用外键
- - '###'
  - 构建 Comment_Table 类
- - '###'
  - 继承
- - '##'
  - 搜索文章
- - '###'
  - 搜索视图
- - '###'
  - 响应用户搜索
- - '###'
  - 搜索模型
- - '###'
  - 使用 LIKE 条件进行搜索
- - '###'
  - 搜索结果视图
- - '###'
  - 从控制器加载搜索结果视图
- - '###'
  - 练习：优化搜索
- - '##'
  - 总结
- - '##'
  - 项目
- - '#'
  - 9. 基础博客：图片与身份验证
- - '##'
  - 学习目标
- - '##'
  - 删除关联表中的条目
- - '###'
  - 理解外键约束
- - '###'
  - 在删除博客条目之前先删除评论
- - '##'
  - 创建图片管理器
- - '###'
  - 显示用于上传图片的表单
- - '###'
  - 快速回顾 `$_FILES` 超全局数组
- - '##'
  - 排版后的文本
- - '###'
  - 上传图片
- - '###'
  - 练习
- - '###'
  - 显示图片
- - '####'
  - 在博客条目中使用图片
- - '##'
  - 通过身份验证增强安全性
- - '##'
  - 在数据库中创建管理员表
- - '##'
  - 使用 BCRYPT 对密码进行哈希处理
- - '###'
  - 单向哈希
- - '###'
  - 足够的安全性
- - '##'
  - 在数据库中添加管理员
- - '###'
  - 构建 HTML 表单
- - '###'
  - 在数据库中保存新管理员
- - '##'
  - 规划登录功能
- - '##'
  - 创建登录表单
- - '##'
  - 对未授权用户隐藏控件
- - '##'
  - HTTP 是无状态的
- - '##'
  - 超全局变量：$_SESSION
- - '##'
  - 使用会话保持状态
- - '##'
  - 退出登录
- - '##'
  - 仅允许授权用户访问
- - '##'
  - 练习
- - '##'
  - 总结
- - '##'
  - 项目
- - '#'
  - 10. 数据仪表盘与游戏
- - '##'
  - 目标
- - '##'
  - 设置数据仪表盘
- - '###'
  - 收集 Microsoft Excel、CSV、JSON 和数据库数据
- - '###'
  - 创建模型数据类
- - '###'
  - 创建下拉列表和文件类型视图
- - '##'
  - PHP 仪表盘控制器实现指南
- - '###'
  - 创建前门控制器和子控制器
- - '###'
  - 其他控制器
- - '###'
  - 创建跳棋游戏的逻辑
- - '##'
  - 排版后内容
- - '##'
  - 计分能力
- - '##'
  - 总结
- - '##'
  - 项目
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K, L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S, T
- - '##'
  - U, V, W
- - '##'
  - X, Y, Z
