name: Beginning CakePHP
name_cn: CakePHP 入门指南
slug: beginning-cakephp
toc:
- - '##'
  - 目录
- - '#'
  - 第一部分：入门
- - '##'
  - 第 1 章：引言
- - '###'
  - CakePHP 入门指南
- - '###'
  - 引言
- - '###'
  - 从新手到专业人士
- - '###'
  - 为什么选择 Cake？
- - '####'
  - 它是 PHP！
- - '####'
  - 快速开发
- - '####'
  - 模型-视图-控制器
- - '###'
  - MVC 提升代码组织性
- - '###'
  - CRUD 操作与 Bake 脚本
- - '###'
  - 脚手架
- - '###'
  - 助手
- - '###'
  - 可定制的元素
- - '###'
  - 庞大的社区
- - '###'
  - 更多特性
- - '###'
  - 总结
- - '##'
  - 第 2 章：安装与运行 CakePHP
- - '###'
  - 简单入门：在 `localhost` 环境运行 Cake
- - '###'
  - 获取 Cake
- - '###'
  - 启动 Cake
- - '###'
  - 权限错误
- - '###'
  - 使用命令行界面
- - '###'
  - Apache AllowOverride 错误
- - '###'
  - 运行设置程序
- - '####'
  - 准备 `tmp` 文件夹以供 Cake 读取和写入临时文件
- - '####'
  - 更改 `Security.salt` 值
- - '####'
  - 输入 MySQL 连接设置
- - '####'
  - 设计您的数据库架构
- - '###'
  - 总结
- - '##'
  - 第 3 章：创建待办事项列表应用程序
- - '###'
  - 探索 MVC 结构
- - '###'
  - Cake 的 MVC 结构
- - '###'
  - 待办事项列表的 MVC 布局
- - '###'
  - 设计并创建数据库
- - '###'
  - 创建模型
- - '###'
  - CakePHP 脚手架与命名约定
- - '#'
  - 第二部分：开发 CakePHP 应用程序
- - '##'
  - 第 4 章：文件命名与数据库设计
- - '###'
  - 约定优于配置
- - '###'
  - 拦截 Cake
- - '###'
  - 从数据库开始
- - '###'
  - MVC 默认行为
- - '###'
  - CakePHP 命名规范与 MVC 结构
- - '###'
  - 命名约定
- - '####'
  - 命名控制器
- - '####'
  - 命名模型
- - '####'
  - 命名视图
- - '###'
  - 控制器中视图文件与操作匹配
- - '###'
  - 表 4-1. `records` 数据库表的 MVC 元素及其命名约定
- - '###'
  - 名称中包含多个单词
- - '###'
  - 表 4-2. `special_orders` 数据库表的 MVC 元素名称
- - '###'
  - 其他 Cake 资源的命名
- - '####'
  - 组件
- - '####'
  - 辅助函数（Helpers）
- - '###'
  - 元素（Elements）
- - '###'
  - 布局（Layouts）
- - '###'
  - 行为（Behaviors）
- - '###'
  - 数据源（DataSource）
- - '###'
  - 最佳实践
- - '####'
  - 避免文件名与 Cake 资源冲突
- - '####'
  - 使用路由而非控制器
- - '###'
  - 以人为本命名动作
- - '###'
  - 谨慎使用 PHP 函数名作为动作名
- - '###'
  - 特性蔓延与 Cake
- - '###'
  - 表关联
- - '###'
  - 数据库设计
- - '###'
  - 属于（Belongs To）
- - '###'
  - '`className` 参数'
- - '###'
  - '`foreignKey` 参数'
- - '###'
  - '`conditions` 参数'
- - '###'
  - '`fields` 参数'
- - '###'
  - “拥有一个”
- - '####'
  - '`className` 参数'
- - '####'
  - '`foreignKey`、`conditions` 和 `fields` 参数'
- - '####'
  - '`dependent` 参数'
- - '###'
  - “拥有多个”
- - '####'
  - '`className`、`foreignKey`、`conditions` 和 `fields` 参数'
- - '####'
  - '`dependent` 参数'
- - '####'
  - '`order` 参数'
- - '####'
  - '`limit` 参数'
- - '####'
  - '`finderQuery` 参数'
- - '###'
  - 测试关联
- - '####'
  - 使用脚手架测试数据库关联
- - '####'
  - 建立表关联的约定
- - '####'
  - “多对多”关联
- - '####'
  - Cake 中的多对多关系
- - '####'
  - 在博客中应用并测试这种关系
- - '##'
  - 第 5 章：在控制台中创建简单视图与烘焙
- - '###'
  - 表关联练习
- - '###'
  - 总结
- - '###'
  - 布局介绍
- - '###'
  - 编写 `default.ctp` 文件
- - '###'
  - 为布局创建样式表
- - '###'
  - 创建独立视图
- - '###'
  - 向控制器添加操作
- - '###'
  - 使用 Bake 创建视图
- - '####'
  - 配置控制台配置文件以运行 Bake
- - '####'
  - 启动 Bake
- - '###'
  - 第二步：烘焙视图
- - '###'
  - 编辑烘焙后的视图
- - '###'
  - 考虑国际化
- - '###'
  - 使用命令加速烘焙
- - '###'
  - 自定义视图
- - '###'
  - 烘焙更多资源
- - '###'
  - 总结
- - '##'
  - 第 6 章：自定义视图
- - '###'
  - 使用 Bake 生成视图和控制器操作可以快速启动应用程序开发。然而，最终你需要更定制化的代码来完善应用程序的功能集。为了让应用程序提供丰富的功能，用户不可避免地会以点击链接和
    HTML 元素、提交表单数据或执行其他交互的形式进行一定程度的操作。当用户与应用程序交互时，他们会发出请求，这些请求会依次经过控制器和视图进行处理。本章将深入探讨这些请求序列，并介绍
    Cake 中那些让你能更精细地控制用户体验的特性。
- - '###'
  - 处理用户交互
- - '###'
  - 一个简单的页面请求
- - '###'
  - 表单提交序列
- - '####'
  - '`$this->data`'
- - '###'
  - 保存表单
- - '###'
  - 为编辑或更新填充表单字段
- - '###'
  - 异步序列
- - '###'
  - 编写单个视图文件
- - '####'
  - 使用调试函数
- - '####'
  - 从头开始自定义视图文件
- - '####'
  - HTML 助手
- - '###'
  - 自定义 HTML 表单
- - '###'
  - 使用其他助手
- - '###'
  - 可读的日期和时间
- - '###'
  - 总结
- - '##'
  - 第 7 章：控制器与模型的使用
- - '###'
  - CakePHP 中的单次操作
- - '###'
  - 构建一个功能丰富的博客
- - '###'
  - 处理操作
- - '####'
  - 在操作中使用变量
- - '###'
  - 请求操作
- - '###'
  - 回调操作在控制器中的工作方式
- - '####'
  - '`afterFilter`'
- - '####'
  - '`beforeRender`'
- - '###'
  - 为博客定制控制器
- - '####'
  - '`recursive` 属性'
- - '####'
  - 分页
- - '####'
  - '`find()` 函数'
- - '###'
  - 操作查询条件
- - '###'
  - 设置查询条件
- - '###'
  - 设置多个条件
- - '###'
  - 显示最新帖子
- - '###'
  - 调整索引视图
- - '###'
  - 查看操作
- - '####'
  - '`read()` 函数'
- - '####'
  - '`setFlash()` 函数'
- - '###'
  - '`redirect()` 函数'
- - '###'
  - 自定义文章显示
- - '###'
  - 为博客创建模型
- - '###'
  - Add 操作
- - '###'
  - '`save()` 函数'
- - '###'
  - 数据验证
- - '###'
  - 使用多重验证
- - '###'
  - 必填字段
- - '###'
  - 在验证时设置错误消息
- - '###'
  - 创建还是更新？
- - '###'
  - 使用内置验证规则
- - '###'
  - 使用多规则
- - '###'
  - 视图中的错误消息
- - '###'
  - 编写自定义模型函数
- - '###'
  - 裁剪结果
- - '####'
  - '`unbindModel()` 函数'
- - '####'
  - '`bindModel()` 函数'
- - '###'
  - Read 视图
- - '###'
  - 总结
- - '##'
  - 第 8 章：实现 Ajax 功能
- - '###'
  - Ajax 的工作原理
- - '###'
  - 使用 Ajax 框架
- - '###'
  - 使用 Ajax 辅助函数
- - '###'
  - Ajax 表单提交
- - '###'
  - 准备 Ajax 助手
- - '####'
  - 安装 Prototype
- - '####'
  - 在应用程序控制器文件中包含 JavaScript 助手
- - '####'
  - 使助手对整个应用程序可用
- - '###'
  - 向博客添加评论
- - '###'
  - 在视图中集成 Ajax
- - '####'
  - 显示评论
- - '###'
  - 使用 Ajax 表单
- - '###'
  - 将 Ajax 融入控制器
- - '###'
  - 为 Ajax 进行渲染
- - '###'
  - 使用其他 Ajax 助手函数
- - '####'
  - '`submit()` 函数'
- - '###'
  - 在视图中使用 `link()` 函数
- - '###'
  - 在控制器和模型中创建投票动作
- - '###'
  - 创建 Votes 视图
- - '###'
  - 使用 Ajax 助手做更多事情
- - '###'
  - Prototype 还是 jQuery
- - '###'
  - 使用 jQuery 上传文件
- - '####'
  - 安装 jQuery 和 Form 插件
- - '###'
  - 创建 Posts Add 操作
- - '###'
  - 创建 Posts Controller Text 操作
- - '###'
  - 编写 Text 视图
- - '###'
  - 更多 Ajax 功能
- - '###'
  - 总结
- - '#'
  - 第三部分：高级 CakePHP
- - '##'
  - 第 9 章：辅助函数
- - '###'
  - 安装辅助函数
- - '###'
  - 使用 Cake 的内置辅助函数
- - '####'
  - 是否要解释每个辅助函数？
- - '####'
  - 使用 HTML 辅助函数
- - '###'
  - '`charset`'
- - '###'
  - '`css`'
- - '###'
  - '`div`'
- - '###'
  - '`docType`'
- - '###'
  - '`image`'
- - '###'
  - '`link`'
- - '###'
  - '`meta`'
- - '###'
  - 排版后的文本
- - '####'
  - '`$html->nestedList()`'
- - '#####'
  - 参数说明
- - '#####'
  - 行为描述
- - '#####'
  - 示例输出
- - '#####'
  - 适用场景
- - '####'
  - '`$html->para()`'
- - '#####'
  - 参数说明
- - '#####'
  - 示例
- - '####'
  - '`$html->style()`'
- - '#####'
  - 参数说明
- - '#####'
  - 应用示例
- - '####'
  - '`tableHeaders` 和 `tableCells`'
- - '####'
  - '`addCrumb` 和 `getCrumbs`'
- - '###'
  - 表 9-4. 表单输入元素选项
- - '###'
  - 表 9-5. 表单输入元素函数
- - '###'
  - 使用其他内置辅助函数
- - '####'
  - Ajax 辅助函数
- - '####'
  - JavaScript 辅助函数
- - '####'
  - 表 9-6. JavaScript 辅助函数中的函数
- - '####'
  - Number 辅助函数
- - '####'
  - 表 9-7. Number 辅助函数
- - '####'
  - Paginator 辅助函数
- - '####'
  - 表 9-8. Paginator 辅助函数
- - '###'
  - RSS 助手
- - '###'
  - Session 助手
- - '###'
  - Text 助手
- - '###'
  - 时间助手
- - '####'
  - 表 9-12. 时间助手函数
- - '###'
  - XML 助手
- - '####'
  - 表 9-13. XML 助手函数
- - '###'
  - 创建自定义助手
- - '####'
  - 使用 App 助手
- - '####'
  - 创建助手文件
- - '####'
  - 使用外部助手函数
- - '####'
  - 为您的博客创建一个助手
- - '#####'
  - 包含 Ajax 助手
- - '###'
  - '`posts/view.ctp` 文件'
- - '####'
  - 编写 Comments 函数
- - '####'
  - 比较辅助程序与元素
- - '####'
  - 扩展评论函数
- - '###'
  - 自定义辅助函数变量
- - '###'
  - 投票标签
- - '###'
  - 总结
- - '##'
  - 第 10 章：路由
- - '###'
  - 基本路由
- - '###'
  - 参数
- - '###'
  - 传递参数（Passed Arguments）
- - '###'
  - 反向路由（Reverse Routing）
- - '###'
  - 查找（Lookups）
- - '###'
  - 在路由器中重写 URL
- - '###'
  - 详细链接（Verbose Linking）
- - '###'
  - 路由动态变更
- - '###'
  - 管理路由
- - '###'
  - 选择管理前缀
- - '###'
  - 链接管理操作和视图
- - '###'
  - 生成管理路由
- - '###'
  - 路由参数
- - '###'
  - 神奇变量
- - '###'
  - 自定义表达式
- - '###'
  - 用于渲染各种标签的辅助程序，请务必在 `PostsController` 或 `AppController` 中包含该辅助程序（关于在控制器中包含辅助程序的更多信息，请参阅第
    9 章）。
- - '###'
  - 自定义路由练习
- - '###'
  - 总结
- - '##'
  - 第 11 章：组件和工具
- - '###'
  - 为什么要使用组件？
- - '###'
  - 使用组件
- - '###'
  - 使用内置组件
- - '####'
  - 身份验证
- - '#####'
  - 设置用户表
- - '#####'
  - 初始化变量
- - '####'
  - 哈希密码
- - '#####'
  - 登录
- - '#####'
  - 确保用户控制器正常工作
- - '#####'
  - 退出登录
- - '#####'
  - 检查用户角色
- - '#####'
  - 使用其他 Auth 参数和函数
- - '#####'
  - 会话
- - '#####'
  - 读取和写入会话变量
- - '#####'
  - 删除和销毁会话
- - '####'
  - Cookie
- - '#####'
  - 设置 Cookie 组件
- - '#####'
  - 写入 Cookie
- - '#####'
  - 读取 Cookie
- - '#####'
  - 删除 Cookie
- - '####'
  - 电子邮件组件
- - '#####'
  - 设置电子邮件布局
- - '#####'
  - 发送电子邮件
- - '#####'
  - 使用电子邮件消息模板
- - '###'
  - 其他组件
- - '####'
  - ACL 组件
- - '####'
  - RequestHandler 组件
- - '####'
  - Security 组件
- - '###'
  - 安全组件
- - '###'
  - 工具类
- - '####'
  - 配置
- - '#####'
  - 读取和写入全局变量
- - '####'
  - 文件与文件夹
- - '#####'
  - 读取文件
- - '#####'
  - 创建新文件
- - '#####'
  - 写入文件
- - '###'
  - 更改文件和文件夹权限
- - '###'
  - 读取文件夹内容
- - '###'
  - 读取文件夹树状结构
- - '###'
  - 复制、创建和删除文件夹
- - '###'
  - 计算文件夹大小
- - '###'
  - 在文件夹中查找文件
- - '###'
  - HTTP Socket
- - '####'
  - 发起 HTTP 请求
- - '###'
  - 使用其他 HTTP Socket 函数
- - '###'
  - 本地化与国际化
- - '###'
  - 使用区域设置文件
- - '###'
  - 翻译字符串
- - '###'
  - 本地化内容
- - '###'
  - 数据清洗
- - '###'
  - 第三方组件
- - '###'
  - 创建自定义组件
- - '###'
  - 使用初始化函数和 Startup 函数
- - '####'
  - 编写供应商文件而非组件
- - '###'
  - 总结
- - '##'
  - 第 12 章：供应商
- - '###'
  - 使用供应商
- - '###'
  - 处理文件名
- - '###'
  - 处理嵌套文件夹
- - '###'
  - 不对第三方脚本做任何假设
- - '###'
  - 在 CakePHP 中引入和使用第三方库
- - '###'
  - 单向脚本
- - '###'
  - 安装第三方脚本
- - '####'
  - 引入 Textile
- - '####'
  - 实例化并运行 Textile
- - '####'
  - 使用 Textile 撰写文章
- - '###'
  - 在 CakePHP 中使用其他框架
- - '####'
  - Zend Framework
- - '###'
  - 在评论添加操作中屏蔽垃圾信息
- - '###'
  - 将文章输出为 PDF 文件
- - '###'
  - 其他 Zend 组件
- - '###'
  - 总结
- - '##'
  - 第 13 章：插件
- - '###'
  - 安装第三方插件
- - '###'
  - 创建自定义插件
- - '####'
  - 插件元素的命名约定
- - '###'
  - 插件命名约定与用法
- - '###'
  - 运行插件操作
- - '###'
  - 使用插件布局
- - '###'
  - 设置文件和文件夹
- - '###'
  - 创建事件表
- - '###'
  - 创建事件模型
- - '###'
  - 创建事件控制器
- - '###'
  - 清单 13-8. 日历事件控制器的初始内容
- - '###'
  - 构建添加和编辑操作
- - '###'
  - 构建索引操作
- - '####'
  - 日历帮助器
- - '#####'
  - 渲染月份的第一周
- - '#####'
  - 渲染第二周和第三周
- - '#####'
  - 渲染第四周
- - '#####'
  - 渲染第五周和第六周
- - '#####'
  - 日历辅助方法实现细节
- - '#####'
  - 渲染事件详情
- - '#####'
  - 构建事件函数
- - '###'
  - 完成索引动作
- - '###'
  - 构建 View 操作
- - '###'
  - 总结
- - '##'
  - 第 14 章：数据源与行为
- - '###'
  - CakePHP 的 MVC 扩展资源
- - '###'
  - 使用数据源和行为扩展模型
- - '###'
  - 使用数据源
- - '###'
  - 使用内置 DataSources
- - '####'
  - '`adodb-[驱动名称]`'
- - '####'
  - '`pear-[驱动名称]`'
- - '###'
  - 构建自定义数据源
- - '####'
  - 创建数据源文件
- - '####'
  - 从最小骨架开始
- - '###'
  - 设置包含数据源的数据库配置
- - '###'
  - 在模型中使用数据源
- - '###'
  - 读取 XML 文件
- - '###'
  - 断开与 XML 文件的连接
- - '###'
  - 解析 XML 文件
- - '###'
  - 查看数据
- - '###'
  - XML 数据源与行为
- - '###'
  - 使用行为
- - '####'
  - 使用 Tree 行为对博客文章进行分类
- - '#####'
  - 向 Tags 表插入所需字段
- - '###'
  - 烘焙新的标签控制器和视图
- - '###'
  - 在模型中使用 Tree 行为
- - '###'
  - 调整视图
- - '####'
  - 当查看标签时获取所有关联文章
- - '###'
  - 使用 Tree 行为的其他函数
- - '####'
  - childCount
- - '####'
  - generateTreeList
- - '####'
  - moveUp 和 moveDown
- - '####'
  - getParentNode 和 getPath
- - '####'
  - recover、removeFromTree、setParent、setup 和 verify
- - '###'
  - 使用 ACL 和 Translate 行为
- - '###'
  - 翻译行为
- - '###'
  - 使用 Containable 行为
- - '###'
  - 附加和分离行为
- - '####'
  - 分离和禁用行为
- - '####'
  - 附加和启用行为
- - '###'
  - 编写自定义行为
- - '###'
  - 设置行为文件
- - '###'
  - 在行为中通过 ConnectionManager 使用 DataSources
- - '###'
  - 在行为中执行回调
- - '###'
  - 编写行为函数时需牢记的要点
- - '###'
  - 总结
- - '##'
  - 第 15 章：收尾应用
- - '###'
  - 设计首页
- - '####'
  - 使用 Pages 控制器生成单一视图
- - '###'
  - 使某个动作成为起始点
- - '###'
  - 生成动态导航
- - '###'
  - 自定义整体设计
- - '###'
  - 调试应用程序
- - '###'
  - 在远程主机上运行应用程序
- - '###'
  - 总结
- - '##'
  - 附录 A：安装问题
- - '###'
  - 在本地主机环境中开发
- - '####'
  - 优先本地主机，其次远程服务器
- - '####'
  - 为何完全远程开发不可取
- - '###'
  - 搭建本地主机环境
- - '####'
  - 在 Mac 系统上搭建
- - '#####'
  - 第三步：运行 MAMP 应用程序
- - '#####'
  - 第四步：配置本地主机根文件夹
- - '#####'
  - 第五步：更改本地主机端口
- - '#####'
  - 第六步：让本地主机更易管理
- - '####'
  - 在 Windows 系统上搭建
- - '#####'
  - 第一步：下载软件
- - '#####'
  - 第二步：运行安装程序
- - '#####'
  - 第三步：打开 XAMPP 控制面板
- - '#####'
  - 第四步：保护本地主机
- - '###'
  - 运行 MySQL
- - '####'
  - 寻找其他 MySQL 工具
- - '#####'
  - CocoaMySQL
- - '#####'
  - MySQL Query Browser
- - '#####'
  - HeidiSQL
- - '####'
  - 运行 MySQL 时的典型设置
- - '#####'
  - 主机
- - '#####'
  - 用户和密码
- - '#####'
  - Socket
- - '#####'
  - 端口
- - '##'
  - 附录 B：CakePHP 与其他框架的对比
- - '###'
  - PHP 框架
- - '###'
  - 使用不同框架
- - '####'
  - CakePHP
- - '####'
  - CodeIgniter
- - '####'
  - Symfony
- - '####'
  - Zend Framework
- - '###'
  - Zend Framework 与 CakePHP 对比分析
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 致谢
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Z
- - '###'
  - 其他
