name: Learn PHP 8
name_cn: PHP 8 学习指南
slug: learn-php-8
toc:
- - '##'
  - 引言
- - '###'
  - 不同之处
- - '###'
  - 给教师的特别说明
- - '###'
  - 代码示例、图片和链接
- - '###'
  - 章节概览
- - '#'
  - 第 1 章：PHP 8 简介
- - '#'
  - 第 2 章：接口、平台与三层架构编程
- - '#'
  - 第 3 章：基础：PHP 8 语法
- - '#'
  - 第 4 章：模块化编程
- - '#'
  - 第 5 章：安全用户界面
- - '#'
  - 第 6 章：异常处理与日志记录
- - '#'
  - 第 7 章：数据对象
- - '#'
  - 第 8 章：身份验证
- - '#'
  - 第 9 章：多功能接口
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 1. PHP 8 简介
- - '##'
  - 章节目标/学生学习成果
- - '###'
  - PHP 7、PHP 7.4+、PHP 8 与 PHP.NET
- - '####'
  - PHP 版本：PHP 7+、PHP 7.4+ 和 PHP 8+
- - '####'
  - 动手练习
- - '####'
  - PHP，JavaScript，CSS，HTML 和 Apache Web 服务器
- - '##'
  - 动手实践
- - '###'
  - 整合起来——PHP、Apache 和 MySQL
- - '####'
  - easyPHP
- - '####'
  - 常见安装问题
- - '#####'
  - 缺少 C# 库
- - '#####'
  - 端口冲突
- - '####'
  - 缺失文件（Missing Files）
- - '####'
  - 无法在 Program Files 目录中安装文件（Cannot Install Files in Program Files Directory）
- - '####'
  - Apache 延迟和挂起（Apache Delays and Hang-Ups）
- - '####'
  - 其他错误（Other Errors）
- - '####'
  - 配置（Configurations）
- - '####'
  - XAMPP
- - '###'
  - 常见安装问题
- - '####'
  - 端口冲突
- - '####'
  - 文件缺失
- - '####'
  - 无法在 Program Files 目录安装文件
- - '####'
  - Apache 延迟和挂起
- - '####'
  - 其他错误
- - '####'
  - 配置
- - '####'
  - Microsoft Internet Information Server
- - '##'
  - 动手实践
- - '###'
  - 使用搜索引擎回答以下问题
- - '###'
  - 测试你的环境
- - '####'
  - 测试你的管理环境
- - '####'
  - 动手实践
- - '####'
  - 测试你的 PHP 环境
- - '####'
  - 常见问题
- - '####'
  - 动手实践
- - '####'
  - 别名（工作）目录
- - '####'
  - 动手实践
- - '####'
  - Notepad++、编辑器和代码测试器
- - '###'
  - Notepad++
- - '####'
  - 其他编辑器
- - '####'
  - 动手实践
- - '##'
  - 章节术语
- - '##'
  - 章节问题与项目
- - '###'
  - 选择题
- - '###'
  - 判断题
- - '###'
  - 简答题/论述题
- - '###'
  - 项目
- - '###'
  - 期末项目
- - '#'
  - 2. 接口、平台与三层架构编程
- - '##'
  - 章节目标/学生学习成果
- - '###'
  - PHP 平台
- - '###'
  - PHP、AJAX 与 CSS——Web 应用程序
- - '####'
  - 动手实践
- - '###'
  - PHP 三层架构
- - '####'
  - 动手实践
- - '####'
  - 界面层
- - '#####'
  - 界面层中的代码部分
- - '#####'
  - 界面层中的该做与不该做
- - '######'
  - 动手实践
- - '####'
  - 业务规则层
- - '#####'
  - 业务规则层中的该做与不该做
- - '######'
  - 动手实践
- - '#####'
  - 3. 为什么业务规则层必须通过接口层间接与用户交互以提供信息？
- - '#####'
  - 数据层
- - '#####'
  - 动手实践
- - '####'
  - 融会贯通
- - '####'
  - 案例研究
- - '#####'
  - 接口层
- - '#####'
  - 业务规则层
- - '#####'
  - 数据层
- - '#####'
  - 动手练习
- - '####'
  - MVC 与依赖注入
- - '##'
  - 章节术语表
- - '##'
  - 章节问题与项目
- - '###'
  - 多项选择
- - '#'
  - 3. 基础篇：PHP 8 语法
- - '##'
  - 变量
- - '##'
  - 数据类型提示
- - '##'
  - 算术运算符
- - '##'
  - 条件语句
- - '##'
  - 函数
- - '###'
  - 动手实践
- - '##'
  - 数组
- - '###'
  - switch 语句 | 联合类型 |
- - '###'
  - include | include_once |
- - '###'
  - require | require_once |
- - '###'
  - try/catch | try 块 |
- - '###'
  - catch 块 | finally 块 |
- - '###'
  - 零异常 | 数组 |
- - '###'
  - 数值数组 | 下标 |
- - '###'
  - array 关键字 | 关联数组 |
- - '###'
  - 键 | 值 |
- - '###'
  - 箭头 (=>) 符号 | 多维数组 |
- - '###'
  - 循环 | for 循环 |
- - '###'
  - while 循环 | 计数变量 |
- - '###'
  - 无限循环 | foreach 循环 |
- - '###'
  - 一维数值数组 | 越界 |
- - '###'
  - array_merge | print_r |
- - '###'
  - 展开运算符 | var_dump |
- - '##'
  - 章节问答与项目
- - '###'
  - 选择题
- - '###'
  - 判断对错
- - '###'
  - 简答/论述题
- - '###'
  - 项目
- - '###'
  - 学期项目
- - '#'
  - 4. 模块化编程
- - '##'
  - 章节目标/学生学习成果
- - '###'
  - PHP 库、扩展、类与对象
- - '####'
  - PHP 扩展
- - '####'
  - 类与对象
- - '####'
  - 创建 PHP 类
- - '###'
  - 文本排版：PHP 类与属性
- - '####'
  - 返回方法
- - '####'
  - 动手实践
- - '####'
  - 设置方法
- - '####'
  - Get 方法
- - '####'
  - 动手实践
- - '###'
  - 构造方法
- - '##'
  - 章节术语
- - '##'
  - 章节问题与项目
- - '###'
  - 选择题
- - '###'
  - 判断题
- - '###'
  - 简答题/论述题
- - '###'
  - 项目
- - '###'
  - 用户输入验证与过滤
- - '####'
  - 动手实践
- - '###'
  - PHP 过滤
- - '####'
  - 动手实践
- - '###'
  - 额外的 HTML 输入安全
- - '###'
  - HTML5 选择列表框和单选按钮
- - '###'
  - 排版后的内容
- - '####'
  - 动手实践
- - '###'
  - 使用 XML 文件验证输入
- - '###'
  - 依赖注入
- - '####'
  - 动手实践
- - '##'
  - 章节术语表
- - '##'
  - 章节问题与项目
- - '###'
  - 选择题
- - '###'
  - 多项选择题
- - '###'
  - 判断题
- - '###'
  - 简答题/论述题
- - '###'
  - 项目
- - '###'
  - 学期项目
- - '#'
  - 5. 安全用户界面
- - '#'
  - 6. 异常处理与日志记录
- - '##'
  - 本章目标/学生学习成果
- - '###'
  - 处理异常
- - '####'
  - 错误
- - '####'
  - 异常
- - '#####'
  - 动手实践
- - '####'
  - 异常与错误处理对比 `if/else` 条件语句
- - '###'
  - 安全性与性能
- - '####'
  - '`__toString` 方法与安全性'
- - '####'
  - 记录异常
- - '####'
  - 操作指南
- - '####'
  - 读取日志文件和文本文件
- - '####'
  - 动手实践
- - '###'
  - 章节术语
- - '###'
  - 章节问答与项目
- - '####'
  - 选择题
- - '#'
  - 7. 数据类
- - '##'
  - 章节目标 / 学生学习成果
- - '##'
  - 数据类
- - '##'
  - JSON 数据
- - '##'
  - MySQL 8+ 的 MySQL 和 NoSQL 数据
- - '##'
  - 动手实践
- - '##'
  - 备份与恢复
- - '###'
  - JSON 备份与恢复
- - '###'
  - MySQL 备份与恢复
- - '##'
  - 连接数据层
- - '###'
  - 接口层、业务规则层和数据层
- - '####'
  - 动手实践
- - '##'
  - 本章术语
- - '##'
  - 本章问题与项目
- - '###'
  - 选择题
- - '###'
  - 判断题
- - '###'
  - 简答题/论述题
- - '###'
  - 项目
- - '###'
  - 学期项目
- - '#'
  - 8. 身份验证
- - '##'
  - 本章目标/学生学习成果
- - '###'
  - 验证与会话
- - '####'
  - JSON 数据
- - '####'
  - MySQL 数据
- - '####'
  - 动手实践
- - '###'
  - 注册
- - '####'
  - JSON 数据
- - '####'
  - MySQL 数据
- - '####'
  - 登录
- - '####'
  - 示例 8-4
- - '####'
  - JSON 数据
- - '####'
  - MySQL 数据
- - '####'
  - 更改密码
- - '####'
  - 示例 8-5
- - '#####'
  - '`changepassword.php` 文件'
- - '####'
  - JSON 数据
- - '####'
  - MySQL 数据
- - '####'
  - 动手实践
- - '##'
  - 章节术语表
- - '##'
  - 章节问题与项目
- - '###'
  - 选择题
- - '###'
  - 判断题
- - '###'
  - 简答题/论述题
- - '###'
  - 项目
- - '###'
  - 课程项目
- - '#'
  - 9. 多功能界面
- - '##'
  - 章节目标/学生学习成果
- - '##'
  - 完整的应用程序
- - '###'
  - 使用 JavaScript 处理数据
- - '####'
  - 备注
- - '#####'
  - 图 9-1
- - '#####'
  - 图 9-2
- - '#####'
  - 图 9-3
- - '#####'
  - 图 9-4
- - '###'
  - 在界面层中更新、删除和插入
- - '####'
  - 动手实践
- - '###'
  - 在业务规则层中实现更新、删除与插入操作
- - '####'
  - 示例 9-4
- - '####'
  - 动手实践
- - '####'
  - 最后修饰
- - '####'
  - 示例 9-5
- - '####'
  - ABC 犬类收容所预约系统逻辑设计
- - '####'
  - 局限性/建议
- - '#####'
  - '`lab.php`'
- - '#####'
  - '`dog_interface.php`'
- - '#####'
  - '`dog.php`'
- - '#####'
  - '`dog_data.php`'
- - '#####'
  - '`register.php`'
- - '#####'
  - 排版后的文档
- - '#####'
  - '`login.php`'
- - '#####'
  - 总体
- - '##'
  - 章节术语
- - '##'
  - 章节问题与项目
- - '###'
  - 选择题
- - '###'
  - 判断题
- - '###'
  - 简答题/论述题
- - '###'
  - 项目
- - '###'
  - 学期项目
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - ABC 犬舍预订系统
- - '###'
  - 管理环境，测试
- - '###'
  - Apache
- - '###'
  - AJAX 与 CSS
- - '###'
  - '`AjaxRequest` 函数'
- - '###'
  - 别名
- - '###'
  - Apache
- - '###'
  - 应用服务器
- - '###'
  - 数组
- - '###'
  - 异步 JavaScript 与 XML（AJAX）
- - '###'
  - 认证过程
- - '##'
  - B
- - '###'
  - 备份/恢复过程
- - '###'
  - 业务规则层
- - '##'
  - C
- - '###'
  - 层叠样式表（CSS）
- - '###'
  - '`change_dog_data` 方法'
- - '###'
  - 条件语句
- - '###'
  - 构造方法
- - '###'
  - '`create_breed_app` 方法'
- - '###'
  - '`create_object` 方法'
- - '###'
  - CSS 代码
- - '##'
  - D
- - '###'
  - 数据库管理系统（DBMS）
- - '###'
  - 数据类
- - '###'
  - 数据集
- - '###'
  - 数据结构
- - '###'
  - 数据层
- - '###'
  - '`datefmt_set_timezone` 方法'
- - '###'
  - '`delete` 方法'
- - '###'
  - '`delete_Process` 方法'
- - '###'
  - '`deleteRecords` 方法'
- - '###'
  - 依赖注入
- - '###'
  - '`display_Process` 方法'
- - '###'
  - '`display_properties` 方法'
- - '###'
  - '`displayRecords` 方法'
- - '###'
  - '`$dog_app` 值'
- - '###'
  - '`dog_data delete` 方法'
- - '###'
  - '`dogdata.php` 文件'
- - '###'
  - '`dog_interface` 程序'
- - '###'
  - '`$dog_size` 属性'
- - '###'
  - 动态构建的数组
- - '##'
  - E
- - '###'
  - EasyPHP
- - '###'
  - '`error_check_dog_app` 方法'
- - '###'
  - '`error_log` 方法'
- - '###'
  - '`error_message` 属性'
- - '###'
  - '`error_message` 字符串'
- - '###'
  - '`errorMessage` 方法'
- - '###'
  - 错误
- - '###'
  - 事件
- - '###'
  - 异常与错误处理
- - '###'
  - 异常
- - '###'
  - PHP
- - '###'
  - 可扩展标记语言（XML）
- - '##'
  - F
- - '###'
  - '`fclose` 方法'
- - '###'
  - '`fgets` 方法'
- - '###'
  - '`file_put_contents` 方法'
- - '###'
  - '`filter_var` 方法'
- - '###'
  - '`fopen` 方法'
- - '###'
  - '`foreach` 循环'
- - '###'
  - 函数
- - '##'
  - G
- - '###'
  - 垃圾回收器
- - '###'
  - '`get_class_methods`'
- - '#'
  - 方法列表
- - '##'
  - A
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y, Z
