name: PHP 7 Solutions
name_cn: PHP 7 解决方案
slug: php-7-solutions
toc:
- - '##'
  - 目录
- - '##'
  - 引言
- - '###'
  - 一个微小但重要的变化
- - '###'
  - 本版还有哪些新内容？
- - '#'
  - 使用示例文件
- - '##'
  - 排版约定
- - '##'
  - 致谢
- - '###'
  - 关于作者及技术审阅者
- - '####'
  - 关于作者
- - '####'
  - 关于技术审阅者
- - '#'
  - 1. 什么是 PHP——我为什么要在意它？
- - '#'
  - PHP 的成长历程
- - '###'
  - 注意
- - '#'
  - PHP 如何使页面动态化
- - '##'
  - 创建能够自主思考的页面
- - '#'
  - PHP 使用和学习的难度如何？
- - '###'
  - 注意
- - '###'
  - 我能直接复制粘贴代码吗？
- - '###'
  - PHP 有多安全？
- - '##'
  - 编写 PHP 需要什么软件？
- - '###'
  - 选择 PHP 编辑器时需要注意什么
- - '##'
  - 那么，让我们开始吧…
- - '#'
  - 2. 准备使用 PHP 工作
- - '#'
  - 检查您的网站是否支持 PHP
- - '##'
  - 为什么不应再使用 PHP 5
- - '##'
  - 决定在何处测试页面
- - '##'
  - 本地测试环境所需的组件
- - '###'
  - 提示
- - '###'
  - 提示
- - '###'
  - 单个程序还是集成包？
- - '##'
  - Windows 系统上的设置
- - '###'
  - 让 Windows 显示文件扩展名
- - '###'
  - 选择 Web 服务器
- - '###'
  - 在 Windows 上安装集成环境包
- - '##'
  - 在 macOS 上进行设置
- - '###'
  - 安装 MAMP
- - '###'
  - 注意
- - '###'
  - 测试与配置 MAMP
- - '###'
  - 注意
- - '###'
  - 提示
- - '##'
  - PHP 文件应放置在何处（Windows 和 Mac）
- - '###'
  - 警告
- - '###'
  - 提示
- - '###'
  - 使用虚拟主机
- - '###'
  - 提示
- - '##'
  - 检查你的 PHP 设置
- - '###'
  - 使用 phpinfo()显示服务器配置
- - '###'
  - 警告
- - '###'
  - 编辑 `php.ini`
- - '##'
  - 接下来做什么？
- - '#'
  - 3. 如何编写 PHP 脚本
- - '##'
  - PHP：全景概览
- - '#'
  - 告知服务器处理 PHP
- - '##'
  - 在网页中嵌入 PHP
- - '##'
  - 将 PHP 存储在外部文件中
- - '##'
  - 使用变量表示变化的值
- - '###'
  - 命名变量
- - '##'
  - 为变量赋值
- - '##'
  - 以分号结束命令
- - '##'
  - 注释脚本
- - '###'
  - 单行注释
- - '#'
  - 这是另一种类型的注释，PHP 引擎会忽略它
- - '##'
  - '菜单部分 ##'
- - '###'
  - 多行注释
- - '##'
  - 使用数组存储多个值
- - '##'
  - PHP 的内置超全局数组
- - '##'
  - 理解何时使用引号
- - '##'
  - 特殊情况：`true`、`false` 和 `null`
- - '##'
  - 做出决策
- - '##'
  - 进行比较
- - '##'
  - 使用缩进和空白提高清晰度
- - '##'
  - 使用循环执行重复任务
- - '##'
  - 使用函数执行预设任务
- - '##'
  - 显示 PHP 输出
- - '##'
  - 使用短 echo 标签
- - '##'
  - 拼接字符串
- - '##'
  - 处理数字
- - '##'
  - 理解 PHP 错误消息
- - '###'
  - 我的页面为什么是空白的？
- - '##'
  - PHP 快速检查清单
- - '#'
  - 本文概述
- - '#'
  - 4. PHP：快速参考
- - '##'
  - 本章涵盖内容
- - '##'
  - 在现有网站中使用 PHP
- - '##'
  - PHP 中的数据类型
- - '##'
  - 检查变量的数据类型
- - '##'
  - 显式更改变量的数据类型
- - '##'
  - 检查变量是否已被定义
- - '##'
  - 使用 PHP 进行计算
- - '###'
  - 算术运算符
- - '###'
  - 使用递增和递减运算符
- - '###'
  - 确定计算顺序
- - '##'
  - 结合计算与赋值
- - '##'
  - 向已有字符串追加内容
- - '##'
  - 关于引号你所需了解的一切——以及更多内容
- - '###'
  - PHP 如何处理字符串中的变量
- - '###'
  - 在双引号内使用转义序列
- - '##'
  - 在字符串中嵌入关联数组元素
- - '##'
  - 使用 heredoc 语法避免转义引号
- - '##'
  - 创建数组
- - '###'
  - 构建索引数组
- - '###'
  - 构建关联数组
- - '##'
  - 创建空数组
- - '##'
  - 多维数组
- - '##'
  - 使用 `print_r()` 检查数组
- - '##'
  - PHP 眼中的真相
- - '###'
  - 显式布尔值
- - '###'
  - 隐式布尔值（“真值”和“假值”）
- - '##'
  - 通过比较两个值进行决策
- - '##'
  - 测试多个条件
- - '#'
  - 排版后内容
- - '##'
  - 注意
- - '##'
  - 使用 switch 语句进行决策链
- - '##'
  - 使用三元运算符
- - '##'
  - 使用 null 合并运算符设置默认值
- - '###'
  - 注意
- - '##'
  - 使用循环重复执行代码
- - '###'
  - 使用 While 和 Do...While 的循环
- - '####'
  - 提示
- - '###'
  - 多功能的 for 循环
- - '##'
  - 使用`foreach`遍历数组和对象
- - '##'
  - 中断循环
- - '##'
  - 使用函数模块化代码
- - '###'
  - 向函数传递值
- - '###'
  - 设置参数的默认值
- - '###'
  - 变量作用域——函数作为黑盒
- - '##'
  - 从函数返回值
- - '##'
  - 生成器——一种持续产出的特殊函数
- - '##'
  - 通过引用传递——改变参数的值
- - '##'
  - 接受可变数量参数的函数
- - '#'
  - 自定义函数的位置
- - '#'
  - 理解 PHP 类与对象
- - '#'
  - 为类与函数可选指定数据类型
- - '#'
  - 处理错误与异常
- - '###'
  - '动态创建新变量  '
- - '###'
  - '现在进入解决方案部分  '
- - '##'
  - '5. 使用包含文件减轻工作量  '
- - '###'
  - '从外部文件包含代码  '
- - '####'
  - '介绍 PHP 包含命令  '
- - '###'
  - 'PHP 查找包含文件的位置  '
- - '####'
  - 'PHP 解决方案 5-1：将菜单和页脚移至包含文件  '
- - '#'
  - PHP Include 文件与文件扩展名安全
- - '##'
  - 页面布局与 Include 文件
- - '##'
  - 操作步骤
- - '##'
  - 问题与解决方案
- - '##'
  - 为 Include 文件选择正确的文件扩展名
- - '##'
  - PHP 解决方案 5-2：测试 include 文件的安全性
- - '##'
  - PHP 解决方案 5-4：根据文件名自动生成页面标题
- - '#'
  - 'PHP 条件语句与变量处理  '
- - '##'
  - '提示  '
- - '##'
  - '注意事项  '
- - '#'
  - 'PHP 解决方案 5-5：处理缺失的变量  '
- - '##'
  - '提示  '
- - '#'
  - '创建内容变化的页面  '
- - '#'
  - 'PHP 解决方案 5-6：自动更新版权声明  '
- - '##'
  - PHP 方案 5-7：显示随机图片
- - '###'
  - PHP 解决方案 5-8：为随机图像添加说明文字
- - '##'
  - 使用包含文件预防错误
- - '###'
  - 检查变量是否存在
- - '###'
  - 检查函数或类是否已定义
- - '##'
  - 在线上网站中抑制错误信息
- - '###'
  - 使用错误控制运算符
- - '###'
  - 在 PHP 配置中关闭 `display_errors`
- - '###'
  - 在单个文件中关闭 `display_errors`
- - '##'
  - PHP 解决方案 5-9：当找不到包含文件时进行重定向
- - '##'
  - 包含文件中的链接
- - '##'
  - 选择包含文件的存放位置
- - '##'
  - 包含功能的安全考虑
- - '##'
  - 调整你的 `include_path`
- - '###'
  - 在 `php.ini` 或 `.user.ini` 中编辑 `include_path`
- - '###'
  - 使用 `.htaccess` 更改 `include_path`
- - '###'
  - 使用 `set_include_path()`
- - '#'
  - 嵌套包含文件
- - '#'
  - 章节回顾
- - '#'
  - 让表单活起来
- - '##'
  - PHP 如何从表单收集信息
- - '###'
  - 理解 `post` 和 `get` 之间的区别
- - '##'
  - 使用 PHP 超全局变量获取表单数据
- - '##'
  - 处理和验证用户输入
- - '###'
  - 创建可复用的脚本
- - '###'
  - PHP 解决方案 6-1：防止自处理表单中的跨站脚本攻击
- - '#'
  - 在表单未完成时保留用户输入
- - '##'
  - PHP 方案 6-3：创建粘性表单字段
- - '##'
  - 过滤潜在攻击
- - '###'
  - PHP 方案 6-4：阻止包含可疑内容的电子邮件地址
- - '##'
  - 发送电子邮件
- - '##'
  - 安全地使用额外的电子邮件头
- - '#'
  - PHP 方案 6-5：添加邮件头并自动设置回复地址
- - '#'
  - PHP 方案 6-6：构建邮件正文并发送邮件
- - '###'
  - 对 `mail()` 进行故障排除
- - '###'
  - 使用第五个参数
- - '###'
  - 处理多项选择表单元素
- - '###'
  - PHP 解决方案 6-7：处理单选按钮组
- - '###'
  - PHP 解决方案 6-8：处理复选框组
- - '##'
  - 'PHP Solution 6-9: 使用下拉选项菜单'
- - '##'
  - 'PHP Solution 6-10: 处理多项选择列表'
- - '##'
  - 'PHP Solution 6-11: 处理单个复选框'
- - '##'
  - 章节回顾
- - '##'
  - 使用 PHP 管理文件
- - '###'
  - 检查 PHP 能否打开文件
- - '####'
  - 提示
- - '###'
  - 在 Windows 上为本地测试创建服务器根目录外的文件夹
- - '###'
  - 在 MacOS 上为本地测试创建服务器根目录外的文件夹
- - '###'
  - 影响文件访问的配置设置
- - '#'
  - 表 7-1 中的两个设置均控制通过 URL（相对于本地文件系统）对文件的访问。第一个设置 `allow_url_fopen` 允许你读取远程文件，但不能将其包含在脚本中。这通常是安全的，因此默认情况下它是启用的。另一方面，`allow_url_include`
    允许你直接将远程文件包含在脚本中。这是一个重大的安全风险，因此 `allow_url_include` 的默认状态是禁用的。
- - '##'
  - 读写文件
- - '##'
  - 单次操作读取文件
- - '###'
  - PHP 解决方案 7-1：获取文本文件的内容
- - '##'
  - 打开和关闭文件以进行读/写操作
- - '###'
  - 表 7-2. 与`fopen()`一起使用的读/写模式
- - '##'
  - 使用 `fopen()` 读取文件
- - '##'
  - PHP 解决方案 7-2：从 CSV 文件中提取数据
- - '##'
  - 在 macOS 上创建的 CSV 文件
- - '##'
  - 使用 `fopen()` 替换内容
- - '##'
  - 使用 `fopen()` 追加内容
- - '##'
  - 写入前锁定文件
- - '##'
  - 注意
- - '##'
  - 防止覆盖现有文件
- - '##'
  - 使用 `fopen()` 进行组合读写操作
- - '##'
  - 移动内部指针
- - '##'
  - 小贴士
- - '##'
  - 探索文件系统
- - '##'
  - 使用 `scandir()` 检查文件夹
- - '##'
  - 使用 `FilesystemIterator` 检查文件夹内容
- - '##'
  - 使用 `RegexIterator` 限制文件类型
- - '##'
  - PHP 解决方案 7-3：构建文件下拉菜单
- - '##'
  - PHP 解决方案 7-4：创建通用文件选择器
- - '##'
  - 访问远程文件
- - '#'
  - 消费新闻与其他 RSS 源
- - '##'
  - 使用 SimpleXML
- - '##'
  - PHP 解决方案 7-5：消费 RSS 新闻源
- - '###'
  - 4. 点击其中一个链接。根据浏览器的设置，文件会下载到默认的下载文件夹，或者会弹出一个对话框询问您如何处理该文件。
- - '###'
  - 章节回顾
- - '##'
  - 8. 处理数组
- - '###'
  - 修改数组元素
- - '####'
  - PHP 解决方案 8-1：使用循环修改数组元素
- - '##'
  - PHP 解决方案 8-2：使用`array_walk()`修改数组元素
- - '#'
  - PHP 解决方案 8-3：使用 `array_map()` 修改数组元素
- - '#'
  - 合并数组
- - '##'
  - 使用数组联合运算符
- - '##'
  - 使用 `array_merge()` 和 `array_merge_recursive()`
- - '##'
  - 将两个索引数组合并为关联数组
- - '##'
  - 比较数组
- - '##'
  - PHP 解决方案 8-4：用逗号连接数组
- - '##'
  - 排序数组
- - '##'
  - PHP Solution 8-5：使用太空船操作符进行自定义排序
- - '##'
  - 使用 `array_multisort()` 进行复杂排序
- - '##'
  - PHP Solution 8-6：使用 `array_multisort()` 排序多维数组
- - '#'
  - 按多条件排序多维数组
- - '#'
  - PHP 解决方案 8-7：查找数组的所有排列
- - '#'
  - 处理数组数据
- - '##'
  - PHP 解决方案 8-8：自动构建嵌套列表
- - '#'
  - Markdown 文档排版结果
- - '##'
  - PHP 解决方案 8-9：从 JSON 提取数据
- - '##'
  - 2.  此数据源包含由旧金山电影委员会编制的市内电影取景地信息。处理 JSON 的挑战之一在于定位所需信息，因为缺乏通用的命名规范。尽管此数据源已按行缩进格式化，但
    JSON 通常为保持紧凑而省略空白。将其转换为多维关联数组可简化识别过程。请在 `ch08` 文件夹中创建一个名为 `json.php` 的 PHP 文件，并添加以下代码（该代码位于
    `json_01.php` 中）：
- - '##'
  - 3.  保存文件并在浏览器中运行该脚本。`$data` 数组非常庞大，包含超过 1,600 部电影的详细信息。用 `<pre>` 标签包裹 `print_r()`
    可以轻松检查其结构，从而定位重要数据所在位置。如图 8-8 所示，顶层数组名为 `meta`，其内嵌套了一个名为 `view` 的子数组，而 `view`
    中又包含了一个名为 `columns` 的子数组。
- - '##'
  - 1.  我们可以使用 PHP 解决方案 8-6“使用 `array_multisort()` 对多维数组排序”中遇到的 `array_column()` 函数来获取列名。然而，`name`
    元素深藏在步骤 2 中存储为 `$data` 的顶层数组中。图 8-8 中的缩进有助于找到正确的子数组作为第一个参数传入。请向脚本中添加以下代码（该代码位于
    `json_02.php` 中）：
- - '##'
  - 2.  使用 `print_r()` 检查是否已提取正确的值，如图 8-10 所示。
- - '##'
  - 3.  现在已获得列名，我们可以遍历 data 子数组，使用 `array_combine()` 将每个元素转换为关联数组。请向脚本中添加以下代码：
- - '##'
  - 4.  `$locations` 现在包含一个关联数组的数组，每个关联数组都包含 JSON 数据源中列出的超过 1,600 个电影取景地的详细信息。要定位特定信息，我们可以使用
    `array_filter()` 函数，该函数接受一个数组和一个回调函数作为参数，并返回过滤后的新数组。
- - '##'
  - 5.  现在我们可以过滤 `$locations` 数组并显示结果，如下所示（完整代码位于 `json_03.php` 中）：
- - '##'
  - 6.  保存脚本并在浏览器中测试。您应该会看到如图 8-11 所示的结果。
- - '##'
  - 7.  将 `$search` 的值更改为旧金山的其他地点名称，例如 Presidio 或 Embarcadero，以查看在那里拍摄的电影名称。
- - '#'
  - 自动将数组元素赋值给变量
- - '##'
  - 使用 `extract()` 函数
- - '###'
  - 注意
- - '##'
  - 使用 `list()`
- - '###'
  - 对 `list()` 使用数组简写语法
- - '##'
  - PHP 解决方案 8-10：使用生成器处理 CSV 文件
- - '#'
  - 使用展开运算符从数组中解包参数
- - '##'
  - PHP 解决方案 8-11：使用展开运算符处理 CSV 文件
- - '##'
  - 章节回顾
- - '#'
  - 9. 上传文件
- - '#'
  - PHP 如何处理文件上传
- - '##'
  - 检查服务器是否支持上传
- - '##'
  - 在表单中添加文件上传字段
- - '##'
  - 理解 $_FILES 数组
- - '###'
  - 检查 $_FILES 数组
- - '#'
  - 1. 文件上传与错误处理
- - '#'
  - 2. 建立上传目录
- - '##'
  - 2.1. 为 Windows 本地测试创建上传文件夹
- - '##'
  - 2.2. 为 macOS 本地测试创建上传文件夹
- - '#'
  - 3. 上传文件
- - '##'
  - 3.1. 将临时文件移动到上传文件夹
- - '#'
  - 4. PHP 解决方案 9-1：创建基本文件上传脚本
- - '##'
  - 注意
- - '##'
  - 说明
- - '##'
  - 创建 PHP 文件上传类
- - '##'
  - 定义 PHP 类
- - '###'
  - 使用命名空间避免命名冲突
- - '##'
  - 注意
- - '###'
  - 导入命名空间类
- - '#'
  - 排版后的 Markdown 文档
- - '##'
  - PHP 解决方案 9-2：创建基本的文件上传类
- - '#'
  - 提示
- - '#'
  - 注意
- - '#'
  - 注意
- - '##'
  - 检查上传错误
- - '##'
  - PHP 方案 9-3：测试错误级别、文件大小和 MIME 类型
- - '##'
  - 更改受保护的属性
- - '###'
  - PHP 解决方案 9-4：允许上传不同类型和大小
- - '#'
  - 上传多个文件
- - '##'
  - '`$_FILES`数组如何处理多文件上传'
- - '##'
  - PHP 解决方案 9-6：调整类以处理多文件上传
- - '##'
  - 使用 Upload 类
- - '##'
  - 文件上传的注意事项
- - '##'
  - 章节回顾
- - '##'
  - 10. 生成缩略图
- - '###'
  - 检查服务器能力
- - '###'
  - 动态处理图像
- - '###'
  - 制作较小的图片副本
- - '####'
  - 准备工作
- - '####'
  - 构建 Thumbnail 类
- - '####'
  - PHP 解决方案 10-1：获取图片详情
- - '#'
  - 如果 `$suffix` 的第一个字符*不是*下划线，则条件为 `true`。这里使用 `strpos()` 函数查找第一个下划线的位置。如果第一个字符是下划线，`strpos()`
    返回的值是 0。然而，如果 `$suffix` 不包含下划线，`strpos()` 会返回 `false`。如第 4 章所述，PHP 将 `0` 视为 `false`，因此条件需要使用“不全等”运算符（两个等号）。所以，如果后缀不是以下划线开头，就添加一个下划线。否则，保留原始值。
- - '##'
  - PHP 解决方案 10-3：计算缩略图的尺寸
- - '##'
  - 使用 GD 函数创建图片的缩放副本
- - '##'
  - PHP 解决方案 10-4：生成缩略图
- - '##'
  - 上传时自动调整图像大小
- - '###'
  - 扩展类
- - '###'
  - PHP 解决方案 10-5：创建 ThumbnailUpload 类
- - '##'
  - 使用 ThumbnailUpload 类
- - '##'
  - 本章回顾
- - '##'
  - 11. 具有记忆功能的页面：简单的登录和多页表单
- - '###'
  - 什么是会话以及它们如何工作
- - '###'
  - '图 11-1  '
- - '###'
  - '图 11-2  '
- - '###'
  - '图 11-3  '
- - '##'
  - '创建 PHP 会话  '
- - '##'
  - '创建和销毁会话变量  '
- - '##'
  - '销毁会话  '
- - '##'
  - '重新生成会话 ID  '
- - '##'
  - “Headers already sent”错误
- - '#'
  - 使用会话限制访问
- - '##'
  - 使用会话限制访问
- - '##'
  - PHP 解决方案 11-1：一个简单的会话示例
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - PHP 解决方案 11-2：使用 `ob_start()` 缓冲输出
- - '##'
  - 使用基于文件的身份验证
- - '###'
  - 使密码安全
- - '###'
  - PHP 解决方案 11-3：创建密码强度检查器
- - '##'
  - PHP 方案 11-4：创建基于文件的用户注册系统
- - '#'
  - PHP 用户注册与密码验证
- - '##'
  - 代码分析与注释
- - '##'
  - 使用`password_verify()`验证哈希密码
- - '###'
  - PHP 解决方案 11-5：构建登录页面
- - '###'
  - PHP 解决方案 11-6：使用会话限制页面访问
- - '###'
  - PHP 解决方案 11-7：创建可重用的退出按钮
- - '###'
  - 保持哈希算法的最新状态
- - '##'
  - 设置会话时限
- - '###'
  - PHP 方案 11-8：在不活动一段时间后结束会话
- - '##'
  - 通过多页表单传递信息
- - '#'
  - PHP 解决方案 11-9：使用会话实现多页表单
- - '##'
  - 章节回顾
- - '##'
  - 12. 数据库入门
- - '#'
  - MySQL 还是 MariaDB？
- - '##'
  - 数据库如何存储信息
- - '##'
  - 主键如何工作
- - '##'
  - 用主键和外键链接表
- - '#'
  - 将信息拆解为小块
- - '#'
  - 良好数据库设计的检查点
- - '#'
  - 使用图形界面
- - '##'
  - 启动 phpMyAdmin
- - '###'
  - 提示
- - '###'
  - 警告
- - '#'
  - 设置 phpsols 数据库
- - '###'
  - 注意
- - '##'
  - MySQL 命名规则
- - '###'
  - 注意
- - '###'
  - 名称的大小写敏感性
- - '#'
  - 使用 phpMyAdmin 创建新数据库
- - '#'
  - 注意
- - '##'
  - 创建特定于数据库的用户帐户
- - '##'
  - 授予用户权限
- - '##'
  - 创建数据库表
- - '###'
  - 定义 Images 表
- - '##'
  - 使用 phpMyAdmin 创建表
- - '##'
  - 向表中插入记录
- - '###'
  - 使用 phpMyAdmin 手动插入记录
- - '###'
  - 从 SQL 文件加载图像记录
- - '##'
  - 创建用于备份和数据传输的 SQL 文件
- - '#'
  - 警告
- - '##'
  - 存储预定义列表
- - '##'
  - 存储二进制数据
- - '##'
  - 章节回顾
- - '#'
  - 13. 使用 PHP 和 SQL 连接数据库
- - '##'
  - 检查远程服务器设置
- - '##'
  - PHP 如何与数据库通信
- - '##'
  - 使用 MySQL 改进版扩展连接
- - '##'
  - 使用 PDO 连接
- - '##'
  - PHP 解决方案 13-1：制作可复用的数据库连接器
- - '###'
  - 提示
- - '##'
  - 解决数据库连接问题
- - '##'
  - 清洗来自数据库的文本结果
- - '##'
  - 查询数据库并显示结果
- - '###'
  - 'PHP 解决方案 13-2: 统计结果集中的记录数 (MySQLi)'
- - '#'
  - PHP 解决方案 13-3：使用 MySQLi 显示 `images` 表
- - '##'
  - MySQLi 连接速查表
- - '#'
  - PHP 解决方案 13-4：统计结果集中的记录数（PDO）
- - '##'
  - 在其他数据库中使用 PDO 统计记录数
- - '#'
  - PHP 解决方案 13-5：使用 PDO 显示 images 表
- - '##'
  - PDO 连接速查表
- - '##'
  - 使用 SQL 与数据库交互
- - '###'
  - 编写 SQL 查询
- - '####'
  - SQL 关键字不区分大小写
- - '####'
  - 空格会被忽略
- - '####'
  - 字符串必须加引号
- - '####'
  - 处理数字
- - '####'
  - 注意
- - '##'
  - 优化 SELECT 查询检索的数据
- - '###'
  - 选择特定列
- - '###'
  - 更改结果排序顺序
- - '###'
  - 搜索特定值
- - '##'
  - 使用通配符搜索文本
- - '##'
  - 理解 SQL 注入的危险
- - '##'
  - PHP 解决方案 13-6：将用户输入的整数插入查询
- - '#'
  - 文档排版结果
- - '##'
  - 使用预处理语句处理用户输入
- - '##'
  - 在 MySQLi 预处理语句中嵌入变量
- - '###'
  - 初始化语句
- - '###'
  - 准备语句
- - '###'
  - 将值绑定到占位符
- - '###'
  - 执行语句
- - '###'
  - 绑定结果（可选）
- - '###'
  - 准备语句（Preparing the statement）
- - '###'
  - 将值绑定到占位符（Binding values to the placeholders）
- - '###'
  - 执行语句（Executing the statement）
- - '###'
  - （可选）绑定结果（Binding the results (optional)）
- - '###'
  - 获取结果（Fetching the result）
- - '##'
  - PHP 解决方案 13-8：在搜索中使用 PDO 预处理语句（Using a PDO Prepared Statement in a search）
- - '##'
  - 'PHP Solution 13-9: 调试 PDO 预处理语句'
- - '##'
  - 'PHP Solution 13-10: 通过用户输入更改列选项'
- - '##'
  - 章节回顾
- - '#'
  - 14. 创建动态相册
- - '##'
  - 为何不将图像存储在数据库？
- - '##'
  - 规划相册
- - '##'
  - 将相册元素转换为 PHP
- - '###'
  - PHP 解决方案 14-1：显示第一张图像
- - '##'
  - 构建动态元素
- - '###'
  - 通过查询字符串传递信息
- - '###'
  - PHP 解决方案 14-2：激活缩略图
- - '##'
  - 创建多列表格
- - '##'
  - PHP 解法 14-3：水平和垂直循环
- - '###'
  - 3. 用于统计列数的代码需要放在显示缩略图的循环开始处的 PHP 代码块内。请按如下方式修改代码：
- - '###'
  - 4. 如果没有更多记录了，你需要检查表格底部是否存在未完成的行。在现有的 `do...while` 循环之后添加一个 `while` 循环。在 MySQLi
    版本中，代码如下所示：
- - '###'
  - 5. 保存页面并在浏览器中重新加载。画廊顶部单行的缩略图现在应该整齐地两两排列，如图 14-4 所示。
- - '##'
  - 对长记录集进行分页
- - '##'
  - 选择子记录集
- - '##'
  - PHP 解法 14-4：显示子记录集
- - '###'
  - 1. 定义 `SHOWMAX` 和用于查找表中总记录数的 SQL 查询。按如下方式修改页面顶部的代码（新代码以粗体显示）：
- - '###'
  - 2. 现在你需要运行新的 SQL 查询。该代码紧接在上一步的代码之后，但根据 MySQL 连接类型的不同而有所不同。对于 MySQLi，使用以下代码：
- - '###'
  - 3. 接下来，设置 `$curPage` 的值。你稍后创建的导航链接将通过查询字符串传递所需页面的值，因此你需要检查 `curPage` 是否在 `$_GET`
    数组中。如果是，则使用该值，但在其前面加上 `(int)` 类型转换运算符以确保它是一个整数。否则，将当前页面设置为 0。在上一步的代码之后立即插入以下代码：
- - '##'
  - 浏览记录子集
- - '##'
  - PHP 解决方案 14-5：创建导航链接
- - '###'
  - 警告
- - '##'
  - 章节回顾
- - '##'
  - 15. 管理内容
- - '###'
  - 设置内容管理系统
- - '###'
  - 创建博客数据库表
- - '###'
  - 创建基本的插入和更新表单
- - '#'
  - 提示
- - '##'
  - 插入新记录
- - '##'
  - PHP 解决方案 15-1：使用 MySQLi 插入新记录
- - '##'
  - PHP 解决方案 15-2：使用 PDO 插入新记录
- - '###'
  - 链接到更新和删除页面
- - '###'
  - PHP 解决方案 15-3：创建指向更新和删除页面的链接
- - '##'
  - 更新记录
- - '###'
  - PHP 解决方案 15-4：使用 MySQLi 更新记录
- - '#'
  - 排版后的内容
- - '##'
  - PHP 解决方案 15-5：使用 PDO 更新记录
- - '###'
  - 注意事项
- - '##'
  - 删除记录
- - '###'
  - 对于 MySQLi：
- - '###'
  - 对于 PDO：
- - '##'
  - 回顾四个基本的 SQL 命令
- - '###'
  - SELECT
- - '###'
  - INSERT
- - '###'
  - UPDATE
- - '##'
  - '`DELETE`'
- - '###'
  - 警告
- - '##'
  - 安全与错误消息
- - '##'
  - 章节回顾
- - '##'
  - 16. 格式化文本和日期
- - '##'
  - 显示文本摘录
- - '###'
  - 提取固定数量的字符
- - '###'
  - 使用`PHP Substr()`函数
- - '###'
  - 在`SQL`查询中使用`LEFT()`函数
- - '#'
  - 处理数据库记录
- - '##'
  - 在完整单词处结束摘要
- - '##'
  - 提取第一段
- - '##'
  - 显示段落
- - '###'
  - 将数据库记录存储为 HTML
- - '###'
  - 将换行符转换为 `<br/>` 标签
- - '###'
  - 创建插入 `<p>` 标签的函数
- - '##'
  - 提取完整句子
- - '##'
  - PHP 方案 16-1：显示文章的前两个句子
- - '#'
  - 一起来约会吧
- - '##'
  - MySQL 如何处理日期
- - '###'
  - 在 `SELECT` 查询中使用 `DATE_FORMAT()` 格式化日期
- - '###'
  - PHP 解法 16-2：格式化 MySQL 日期或时间戳
- - '##'
  - 日期的加减运算
- - '###'
  - PHP 解法 16-3：显示过去一周内更新的项目
- - '###'
  - 3. 保存并在浏览器中重新加载页面。
- - '###'
  - 4. 打开 `blog_list_mysqli.php` 或 `blog_list_pdo.php`，选择一个未显示在 `blog.php` 中的项目并编辑它。
- - '##'
  - 向 MySQL 插入日期
- - '##'
  - PHP 解决方案 16-4：为 MySQL 输入验证和格式化日期
- - '###'
  - 1. 执行所有检查的代码是 `utility_funcs.php` 中的一个自定义函数。它看起来像这样：
- - '###'
  - 2. 为了测试，请将此代码添加到页面主体中表单的正下方：
- - '###'
  - 3. 保存页面，输入日期并点击“转换”进行测试。
- - '###'
  - 4. 创建一个名为 `date_converter.php` 的页面，并插入一个包含以下代码的表单（或使用 `ch16` 文件夹中的 `date_converter_01.php`）：
- - '##'
  - 在 PHP 中处理日期
- - '###'
  - 设置默认时区
- - '##'
  - 创建 DateTime 对象
- - '##'
  - 在 PHP 中格式化日期
- - '##'
  - 从自定义格式创建 DateTime 对象
- - '##'
  - 在 date() 和 DateTime 类之间进行选择
- - '###'
  - 使用相对日期处理溢出问题
- - '###'
  - 使用 `DateTimeZone` 类
- - '###'
  - 使用 `DateInterval` 类添加和减去固定时间段
- - '###'
  - 使用 `diff()` 方法查找两个日期之间的差异
- - '###'
  - 使用 `DatePeriod` 类计算重复日期
- - '##'
  - 章节回顾
- - '##'
  - 17. 从多个表中提取数据
- - '###'
  - 理解表关系
- - '#'
  - 关系数据库中的表关联与外部键
- - '##'
  - 主键、外键与关系类型
- - '##'
  - 多对多关系
- - '##'
  - 引用完整性
- - '##'
  - 将图片链接到文章
- - '###'
  - 修改现有表结构
- - '##'
  - PHP 解决方案 17-1：向表中添加额外列
- - '##'
  - 向表中插入外键
- - '##'
  - PHP 解决方案 17-2：添加 image 外键（MySQLi）
- - '#'
  - 排版后的文本
- - '##'
  - MySQLi 实现
- - '##'
  - 'PHP Solution 17-3: 添加图片外键 (PDO)'
- - '#'
  - 条件语句与数据库查询
- - '##'
  - 用于图片选择的条件语句
- - '##'
  - 保存并测试页面
- - '##'
  - 从多张表中选取记录
- - '##'
  - PHP 解决方案 17-4：构建详情页面
- - '###'
  - 查找没有匹配外键的记录
- - '##'
  - 创建智能链接
- - '###'
  - PHP 解决方案 17-5：返回到导航系统中的同一位置
- - '##'
  - 章节回顾
- - '##'
  - 18. 管理多个数据库表
- - '###'
  - 维护参照完整性
- - '#'
  - 支持事务与外键约束
- - '##'
  - PHP 解决方案 18-1：检查是否支持 InnoDB
- - '##'
  - 向多张表插入记录
- - '##'
  - 创建交叉引用表
- - '##'
  - PHP 解决方案 18-4：将数据插入多个表
- - '##'
  - PDO 版本的主要差异
- - '##'
  - 在多表中更新和删除记录
- - '#'
  - 更新交叉引用表中的记录
- - '##'
  - PHP 解决方案 18-5：将分类添加到更新表单
- - '##'
  - 将多个查询作为事务中的块处理
- - '###'
  - 在 MySQLi 中使用事务
- - '###'
  - 在 PDO 中使用事务
- - '##'
  - PHP 解决方案 18-6：将表转换为 InnoDB 存储引擎
- - '##'
  - PHP 解决方案 18-7：将更新序列封装在事务中（MySQLi）
- - '#'
  - PHP 解决方案 18-8：在事务中包装更新序列（PDO）
- - '#'
  - 处理后的文本
- - '##'
  - 删除时保持参照完整性
- - '##'
  - PHP Solution 18-9：设置外键约束
- - '##'
  - 创建带有外键约束的删除脚本
- - '##'
  - 创建没有外键约束的删除脚本
- - '##'
  - 章节回顾
- - '##'
  - 19. 使用数据库进行用户认证
- - '#'
  - 第 11 章：用户身份验证与密码存储
- - '##'
  - 选择密码存储方法
- - '##'
  - 使用密码哈希处理
- - '###'
  - 创建存储用户详细信息的表
- - '###'
  - 在数据库中注册新用户
- - '####'
  - PHP 解决方案 19-1：创建用户注册表单
- - '##'
  - PHP 解决方案 19-2：使用数据库验证用户凭证
- - '##'
  - 使用密钥加密
- - '###'
  - 创建存储用户详细信息的表
- - '###'
  - 注册新用户
- - '##'
  - 使用双向加密进行用户身份验证
- - '###'
  - 解密密码
- - '###'
  - 更新用户详细信息
- - '###'
  - 下一步做什么？
- - '##'
  - 索引
- - '###'
  - A
- - '#'
  - 函数与类参考文档
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '###'
  - 类
- - '###'
  - 逗号分隔值 (CSV) 文件
- - '###'
  - 连接运算符
- - '###'
  - 内容管理系统
- - '##'
  - D
- - '###'
  - 数据库设计
- - '###'
  - 数据源名称 (DSN)
- - '###'
  - 日期和时间格式化
- - '###'
  - 转储
- - '###'
  - 动态元素
- - '##'
  - E
- - '###'
  - 邮件头注入
- - '###'
  - 邮件头
- - '###'
  - 加密方法
- - '###'
  - 错误消息，PHP
- - '##'
  - F
- - '###'
  - 反馈表单，PHP
- - '#'
  - '`radio-button groups`（单选按钮组）'
- - '#'
  - 排版后的 Markdown 文档
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
